### ISSUE TITLE
Panic  when registering a service that does not exist

### ISSUE THREAD

**Issue by gaodb1210** [polarismesh/polaris#102]
**Describe the bug**
 when i try to register a service instance，It is found that panic is thrown when the registered service does not exist

err log:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaababb]

goroutine 114 [running]:
github.com/polarismesh/polaris-server/store/boltdbStore.(*serviceStore).GetSourceServiceToken(0xc00016cb90, 0xc0004048e8, 0x5, 0xc0004048f0, 0x7, 0x0, 0x0, 0x0)
        /home/runner/work/polaris/polaris/store/boltdbStore/service.go:181 +0xbb
github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).batchVerifyInstances(0xc0000ce630, 0xc000482420, 0xc000482420, 0x0, 0x0, 0xc00004be00)
        /home/runner/work/polaris/polaris/naming/batch/instance.go:385 +0x6ce
github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).registerHandler(0xc0000ce630, 0xc0000a3700, 0x1, 0x20, 0xc000063550, 0x10f9001)
        /home/runner/work/polaris/polaris/naming/batch/instance.go:226 +0x2b5
github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).storeWorker(0xc0000ce630, 0xd3f838, 0xc000063540, 0x20)
        /home/runner/work/polaris/polaris/naming/batch/instance.go:181 +0x24b
created by github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).Start
        /home/runner/work/polaris/polaris/naming/batch/instance.go:93 +0x1b5

**Environment**
- Version: v1.2.1
- OS: linux

**Comment by chuntaojun** [comment]
you can see here : https://github.com/polarismesh/polaris/issues/95

**Comment by gaodb1210** [comment]
ok
