### ISSUE TITLE
支持envoy 独立网关模式

### ISSUE THREAD

**Issue by lei32323** [polarismesh/polaris#1047]
**What is the feature you want to add?**
北极星通过xds协议下发单个domain下多path的访问方式

**Why do you want to add this feature?**
通过单个域名+服务名称 访问北极星的服务
具体访问如下：
`https://envoy.hostname/{serviceName1}/list`
`https://envoy.hostname/{serviceName2}/list`

**How to implement this feature?**
北极星下发xds部分信息如下
![image](https://user-images.githubusercontent.com/16314374/228099981-71be3e94-288a-49e8-9108-071de152711c.png)

**Comment by chuntaojun** [comment]
如果 envoy 以 gateway 的模式从北极星的 xds server 拉取数据时，则需要在 bootstrap 中参考上述示例设置 node 属性
