### ISSUE TITLE
完善北极星的OpenAPI swagger 文档

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#1064]
代码路径：apiserver/httpserver/docs

完善各个OpenAPI的文档定义，包括参数设置、类型、Response响应，错误码类型

**Comment by xywf221** [comment]
Response响应这里有个问题反馈 swagger文档写的响应类型是json这里手动调用返回的类型是 `text/plain` 大致看了下代码发现是写死了

**Comment by chuntaojun** [comment]
只是 Content-Type 吗？
