### ISSUE TITLE
优化项目内的测试用例，使得测试用例之间可以并行执行，减少CI执行时间

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#1073]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by shichaoyuan** [comment]
像 eventhub 这种全局的模块可能得先改一下

**Comment by chuntaojun** [comment]
> Member

要不来优化下？

**Comment by shichaoyuan** [comment]
> > Member
> 
> 要不来优化下？

ok 我来试一下
