### ISSUE TITLE
修改auth.option.salt的值无法正常登陆console

### ISSUE THREAD

**Issue by 123libohan** [polarismesh/polaris#1083]
我在polaris-server的配置文件中，修改了auth.option.salt中的值为32位的大写字母和数字，在console的配置文件中也修改了这个salt的值，发现登录不了console，修改回默认的可以登录，这个是不是修改这个salt的值吗？
polaris-server的配置文件如下：
auth:
  # Inspection plug -in
  name: defaultAuth
  option:
    # Token encrypted SALT, you need to rely on this SALT to decrypt the information of the Token when analyzing the Token
    # The length of SALT needs to satisfy the following one：len(salt) in [16, 24, 32]
    salt: 7607F1BECB09645A198DE69694B6EB94

polaris-console的配置文件如下：
webServer:
  mode: "release"
  listenIP: "0.0.0.0"
  listenPort: 8080
  jwt:
    secretKey: "7607F1BECB09645A198DE69694B6EB94"
    expired: 1800

**Comment by chuntaojun** [comment]
要修改 auth.option.salt，参考文档进行修改：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%BD%BF%E7%94%A8/%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6/%E7%AD%96%E7%95%A5/

**Comment by 123libohan** [comment]
> 要修改 auth.option.salt，参考文档进行修改：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%BD%BF%E7%94%A8/%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6/%E7%AD%96%E7%95%A5/

非常感谢，我参考着进行修改试试
