### ISSUE TITLE
polaris standalone wrong usage of `local` in prometheus-help.sh

### ISSUE THREAD

**Issue by evil0th** [polarismesh/polaris#1092]
**Describe the bug**
./prometheus-help.sh: line 20: local: can only be used in a function

**To Reproduce**
exec command `./prometheus-help.sh stop`

**Expected behavior**
no error

**Environment**
- Version: v1.16.2
- OS: macOS, bash or zsh

**Additional context**
Nop

**Comment by chuntaojun** [comment]
will be optimized in version 1.17
