### ISSUE TITLE
lock bootstrap error

### ISSUE THREAD

**Issue by sun2008mt** [polarismesh/polaris#1127]
**Describe the bug**
Contaners of redis and mysql start successfully, but polaris-server fails with error `lock bootstrap error`.
Detailed infomation refers to `Additional context`

**To Reproduce**
1. clone the latest source code of polaris
2. Refer to [docker-compose](https://github.com/polarismesh/polaris/tree/main/release/standalone/docker-compose)
3. just modify the version of the images, namely `:##POLARIS_SERVER_VERSION##` to `latest`(actual version is v1.17.1)

**Expected behavior**
polaris-server container starts successfully

**Environment**
- Version: v1.17.1
- OS: Ubuntu22.04

**Additional context**
2023/05/15 17:26:03 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
[INFO] load config from conf/polaris-server.yaml
bootstrap:
  logger:
    HistoryLogger:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/operation/polaris-history.log
      errorRotateOutputPath: log/operation/polaris-history-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 24
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    apiserver:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-apiserver.log
      errorRotateOutputPath: log/runtime/polaris-apiserver-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    auth:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-auth.log
      errorRotateOutputPath: log/runtime/polaris-auth-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    cache:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-cache.log
      errorRotateOutputPath: log/runtime/polaris-cache-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    config:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-config.log
      errorRotateOutputPath: log/runtime/polaris-config-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    default:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-default.log
      errorRotateOutputPath: log/runtime/polaris-default-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    discoverEventLocal:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/event/polaris-discoverevent.log
      errorRotateOutputPath: log/event/polaris-discoverevent-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    discoverLocal:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/statis/polaris-discoverstat.log
      errorRotateOutputPath: log/statis/polaris-discoverstat-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    healthcheck:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-healthcheck.log
      errorRotateOutputPath: log/runtime/polaris-healthcheck-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    local:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/statis/polaris-statis.log
      errorRotateOutputPath: log/statis/polaris-statis-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    naming:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-naming.log
      errorRotateOutputPath: log/runtime/polaris-naming-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    store:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-store.log
      errorRotateOutputPath: log/runtime/polaris-store-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    token-bucket:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-ratelimit.log
      errorRotateOutputPath: log/runtime/polaris-ratelimit-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
    xdsv3:
      outputPaths: []
      errorOutputPaths: []
      rotateOutputPath: log/runtime/polaris-xdsv3.log
      errorRotateOutputPath: log/polaris-xdsv3-error.log
      rotationMaxSize: 100
      rotationMaxAge: 7
      rotationMaxBackups: 10
      jsonEncoding: false
      loggrpc: false
      rotationMaxDurationForHour: 0
      outputLevel: info
      stackTraceLevel: ""
      disableLogCaller: false
      onlyContent: false
  startInOrder:
    key: sz
    open: true
  polaris_service:
    enable_register: true
    probe_address: mysql:3306
    isolated: false
    heartbeat_interval: 0
    services:
    - name: polaris.checker
      namespace: ""
      protocols:
      - service-grpc
      metadata: {}
apiservers:
- name: service-eureka
  option:
    connLimit:
      maxConnLimit: 10240
      maxConnPerHost: 1024
      openConnLimit: false
      purgeCounterExpired: 5s
      purgeCounterInterval: 10s
      whiteList: 127.0.0.1
    deltaExpireInterval: 60
    listenIP: 0.0.0.0
    listenPort: 8761
    namespace: default
    owner: polaris
    refreshInterval: 10
    unhealthyExpireInterval: 180
  api: {}
- name: api-http
  option:
    connLimit:
      maxConnLimit: 5120
      maxConnPerHost: 128
      openConnLimit: false
      purgeCounterExpired: 5s
      purgeCounterInterval: 10s
      whiteList: 127.0.0.1
    enablePprof: true
    enableSwagger: true
    listenIP: 0.0.0.0
    listenPort: 8090
  api:
    admin:
      enable: true
      include: []
    client:
      enable: true
      include:
      - discover
      - register
      - healthcheck
    config:
      enable: true
      include:
      - default
    console:
      enable: true
      include:
      - default
- name: service-grpc
  option:
    connLimit:
      maxConnLimit: 5120
      maxConnPerHost: 128
      openConnLimit: false
    enableCacheProto: true
    listenIP: 0.0.0.0
    listenPort: 8091
    sizeCacheProto: 128
    tls:
      certFile: ""
      keyFile: ""
      trustedCAFile: ""
  api:
    client:
      enable: true
      include:
      - discover
      - register
      - healthcheck
- name: config-grpc
  option:
    connLimit:
      maxConnLimit: 5120
      maxConnPerHost: 128
      openConnLimit: false
    listenIP: 0.0.0.0
    listenPort: 8093
  api:
    client:
      enable: true
      include: []
- name: xds-v3
  option:
    connLimit:
      maxConnLimit: 10240
      maxConnPerHost: 128
      openConnLimit: false
    listenIP: 0.0.0.0
    listenPort: 15010
  api: {}
cache:
  open: true
  diffTime: 0s
  resources:
  - name: service
    option:
      disableBusiness: false
      needMeta: true
  - name: instance
    option:
      disableBusiness: false
      needMeta: true
  - name: routingConfig
    option: {}
  - name: rateLimitConfig
    option: {}
  - name: circuitBreakerConfig
    option: {}
  - name: users
    option: {}
  - name: strategyRule
    option: {}
  - name: namespace
    option: {}
  - name: client
    option: {}
  - name: configFile
    option:
      expireTimeAfterWrite: 3600
  - name: faultDetectRule
    option: {}
namespace:
  autoCreate: true
naming:
  auth:
    open: false
  batch:
    clientDeregister:
      concurrency: 64
      maxBatchCount: 32
      open: true
      queueSize: 10240
      waitTime: 32ms
    clientRegister:
      concurrency: 64
      maxBatchCount: 1024
      open: true
      queueSize: 10240
      waitTime: 32s
    deregister:
      concurrency: 128
      maxBatchCount: 128
      open: true
      queueSize: 10240
      waitTime: 32ms
    register:
      concurrency: 128
      dropExpireTask: true
      maxBatchCount: 128
      open: true
      queueSize: 10240
      taskLife: 30s
      waitTime: 32ms
config:
  open: true
  cache: {}
healthcheck:
  open: true
  service: polaris.checker
  slotNum: 30
  localHost: ""
  minCheckInterval: 1s
  maxCheckInterval: 30s
  clientCheckInterval: 0s
  clientCheckTtl: 0s
  checkers:
  - name: heartbeatRedis
    option:
      concurrency: 200
      connectTimeout: 200ms
      idleTimeout: 120s
      kvAddr: redis:6379
      kvPasswd: polaris
      minIdleConns: 30
      msgTimeout: 200ms
      poolSize: 200
  batch:
    heartbeat:
      concurrency: 64
      maxBatchCount: 32
      open: true
      queueSize: 10240
      waitTime: 32ms
maintain:
  jobs: []
store:
  name: defaultStore
  option:
    master:
      connMaxLifetime: 300
      dbAddr: mysql:3306
      dbName: polaris_server
      dbPwd: polaris
      dbType: mysql
      dbUser: root
      maxIdleConns: 50
      maxOpenConns: 300
      txIsolationLevel: 2
auth:
  name: defaultAuth
  option:
    clientOpen: false
    consoleOpen: true
    salt: polarismesh@2021
plugin:
  cmdb:
    name: ""
    option: {}
  ratelimit:
    name: token-bucket
    option:
      api-limit:
        apis:
        - name: POST:/v1/naming/services
          rule: store-write
        - name: PUT:/v1/naming/services
          rule: store-write
        - name: POST:/v1/naming/services/delete
          rule: store-write
        - name: GET:/v1/naming/services
          rule: store-read
        - name: GET:/v1/naming/services/count
          rule: store-read
        open: false
        rules:
        - limit:
            bucket: 2000
            open: true
            rate: 1000
          name: store-read
        - limit:
            bucket: 1000
            open: true
            rate: 500
          name: store-write
      instance-limit:
        global:
          bucket: 200
          rate: 100
        open: true
        resource-cache-amount: 1024
      ip-limit:
        global:
          bucket: 300
          open: true
          rate: 200
        open: true
        resource-cache-amount: 1024
        white-list:
        - 127.0.0.1
      remote-conf: false
  history:
    name: ""
    option: {}
    entries:
    - name: HistoryLogger
      option: {}
  statis:
    name: ""
    option: {}
    entries:
    - name: local
      option:
        interval: 60
    - name: prometheus
      option: {}
  discoverStatis:
    name: discoverLocal
    option:
      interval: 60
      outputPath: ./discover-statis
  parsePassword:
    name: ""
    option: {}
  whitelist:
    name: ""
    option: {}
  meshResourceValidate:
    name: ""
    option: {}
  discoverEvent:
    name: ""
    option: {}
    entries:
    - name: discoverEventLocal
      option: {}
[Store][Info] current use store plugin : defaultStore
[ERROR] bootstrap fail: lock bootstrap error

**Comment by sun2008mt** [comment]
将 `store/mysql/scripts/polaris_server.sql` 文件拷贝到 `release/standalone/docker-compose/mysql` 目录下能够启动成功，应该是初始化脚本缺失的问题吧

**Comment by chuntaojun** [comment]
行，我这里修复处理下

**Comment by sun2008mt** [comment]
我刚开始也是以为数据是包含在 polaris-server 镜像中的，但是试了好几次行，我用的镜像好像是 v1.17.1，而且是 `polarismesh/polaris-server:latest`，不是 standalone 版本的(standalone 版本没问题)

**Comment by chuntaojun** [comment]
> 我刚开始也是以为数据是包含在 polaris-server 镜像中的，但是试了好几次都不行，我用的镜像好像是 v1.17.1，而且是 `polarismesh/polaris-server:latest`，不是 standalone 版本的(standalone 版本没问题)

指定为 1.17.0 吧，另外 polaris-default 和 polaris-store 有其他报错日志吗

**Comment by sun2008mt** [comment]
没其他问题，那应该是镜像打包问题，standalone 最新版好像是 v1.17.0

**Comment by chuntaojun** [comment]
1.17.1 已经发布，可以再看看，我自己测试没有发现类似的问题

**Comment by sun2008mt** [comment]
还是同样的问题，确定是使用的 [docker-compose](https://github.com/polarismesh/polaris/tree/main/release/standalone/docker-compose) 这个文件吗? 原因我也找了，是 `mysql` 镜像的 `./mysql:/docker-entrypoint-initdb.d` 这一句没有对应的文件，因此 `mysql` 容器启动后内部只有 `polaris_server` 数据库，但是库里面没有相关表和数据。启动 `polaris-server` 容器后就直接出现 `lock bootstrap error` 问题并一直重启。将 `store/mysql/scripts/polaris_server.sql` 文件拷贝到 `release/standalone/docker-compose/mysql` 目录下面，`mysql` 里面有表和数据后就没问题了

**Comment by chuntaojun** [comment]
> 还是同样的问题，确定是使用的 [docker-compose](https://github.com/polarismesh/polaris/tree/main/release/standalone/docker-compose) 这个文件吗? 原因我也找了，是 `mysql` 镜像的 `./mysql:/docker-entrypoint-initdb.d` 这一句没有对应的文件，因此 `mysql` 容器启动后内部只有 `polaris_server` 数据库，但是库里面没有相关表和数据。启动 `polaris-server` 容器后就直接出现 `lock bootstrap error` 问题并一直重启。将 `store/mysql/scripts/polaris_server.sql` 文件拷贝到 `release/standalone/docker-compose/mysql` 目录下面，`mysql` 里面有表和数据后就没问题了

你应该走release包：https://github.com/polarismesh/polaris/releases/download/v1.17.1/polaris-standalone-release_v1.17.1.docker-compose.zip

**Comment by sun2008mt** [comment]
release 包确实有，那应该就没问题了

**Comment by chuntaojun** [comment]
> release 包确实有，那应该就没问题了，不过源码中应该也放一份吧，一般 clone 源码的也不少，或者 README 中需要说明一下

在 README 中说明下我们
