### ISSUE TITLE
docker部署的polaris-standalone单机版本重启后可观测性部分无法使用

### ISSUE THREAD

**Issue by Abandoned9** [polarismesh/polaris#1142]
**Describe the bug**
docker部署的polaris-standalone单机版本重启后可观测性部分无法使用
。`/api/v1/query_range?query=sum` 接口报错502，进bash里面看过普罗米修斯应该是启动了的

**To Reproduce**
docker部署，在portainer重启过后就这样了

**Expected behavior**
刚刚部署完成的时候是正常使用，后来服务器重启了，再次启动docker的时候就这样了

**Environment**
- Version: 1.17.0
- OS: debian11，docker

**Additional context**
无，如果还需什么补充可以告诉我

**Comment by chuntaojun** [comment]
容器是先 stop 后在 start 对吧？

**Comment by chuntaojun** [comment]
会在1.17.2版本进行修复改问题

**Comment by Abandoned9** [comment]
> 会在1.17.2版本进行修复改问题

hi，能push一下docker镜像吗，dockerhub上面的polarismesh/polaris-standalone已经有一个月没有更新过了

**Comment by chuntaojun** [comment]
> > 会在1.17.2版本进行修复改问题
> 
> hi，能push一下docker镜像吗，dockerhub上面的polarismesh/polaris-standalone已经有一个月没有更新过了

有版本发布的话会更新的
