### ISSUE TITLE
bootstrap/server.go#StartDiscoverComponents中batchConfig设置

### ISSUE THREAD

**Issue by qnnn** [polarismesh/polaris#1190]
这个是写错了吗
![image](https://github.com/polarismesh/polaris/assets/65326092/e2b9c8de-4f1b-4c47-bd4a-f672f9245b0a)

**Comment by chuntaojun** [comment]
确实是有问题

**Comment by chuntaojun** [comment]
可以来一个PR修复下

**Comment by qnnn** [comment]
> 可以来一个PR修复下

好的大佬
