### ISSUE TITLE
熔断修改规则中的服务名，项目运行的时候还是按照修改之前的规则熔断

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#1197]
**Describe the bug**

熔断修改规则中的服务名，项目运行的时候还是按照修改之前的规则熔断

**To Reproduce**

1.在相同命名空间下有主调A，被调B两个服务
2.规则 A->B，配置熔断降级body aaaaa 然后启用规则 rule 服务级熔断
3.多次请求之后熔断打开
4.修改规则 rule 的服务名 A->A1,B->B2,修改熔断降级body bbbbb
5.多次请求之后熔断打开，返回服务降级 aaaaa
6.查看backup中的熔断规则文件 rule的 source中service为A destination中service为B

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
assign https://github.com/Tencent/spring-cloud-tencent/issues/1081
