### ISSUE TITLE
希望Polaris支持 url rewrite 特性

### ISSUE THREAD

**Issue by amyson** [polarismesh/polaris#1218]
**What is the feature you want to add?**
希望Polaris支持 url rewrite 特性

**Why do you want to add this feature?**
从nginx迁移过来的应用，有较多的 rewrite 规则；并且 Envoy 也具备 rewrite 特性……
Polaris 作为 Envoy 的控制面使用时需要具备 rewrite 配置能力。

**Comment by chuntaojun** [comment]
同该 issue：https://github.com/polarismesh/polaris/issues/1244
