### ISSUE TITLE
进行心跳实例分派时，为server节点设置的权重未生效

### ISSUE THREAD

**Issue by qnnn** [polarismesh/polaris#1242]
**Describe the bug**
设置其中两个server节点权重为0
![7db5f306a2b3baf5dfa26bb41758cdc](https://github.com/polarismesh/polaris/assets/65326092/5bd34296-ee27-4cd2-a008-7f767406e637)
在加载服务端节点列表时，其权重均被默认设为100
![b3dcffe0109b4e7edc3d806aadcb28f](https://github.com/polarismesh/polaris/assets/65326092/d503738b-6a6e-4145-a67d-797ea72c8b9c)

![e4ef13ab7da4935a314cae96021e71d](https://github.com/polarismesh/polaris/assets/65326092/50ac2c73-5e33-4a44-8c48-f2caad6b9c92)

每个server节点权重默认被设置为常量100
![image](https://github.com/polarismesh/polaris/assets/65326092/33b6a7eb-2658-45d3-970f-d77d37518e1a)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by WTIFS** [comment]
我这边也发现了，就近路由配置的地区也不能生效，似乎是 1.17.3 引入的 bug，1.17.2 就没有问题

**Comment by qnnn** [comment]
> 我这边也发现了，就近路由配置的地区也不能生效，似乎是 1.17.3 引入的 bug，1.17.2 就没有问题

咦，我这边1.17.2也有问题。是同个问题吗

**Comment by WTIFS** [comment]
> 

看了一下，确实不是一个问题。。我这个问题在 #1238 里修复了，不过还没合入 master
