### ISSUE TITLE
希望能够添加更多网关特性

### ISSUE THREAD

**Issue by Cloud-Yao** [polarismesh/polaris#1244]
**What is the feature you want to add?**
希望能够在Polaris中增加更多网关的特性，例如JWT认证，基于Key的认证/限流，自定义应答，请求路径重写，WAF防护，域名管理，证书管理等等。
之前看到阿里开源的一个Higress网关将南北流量和东西流量进行统一管理，希望在这边也能够借鉴一下。目前我看的网关支持的是Envoy Gateway和Nginx Gateway，但是好像都没有上述的功能。
**Why do you want to add this feature?**
阿里的那一套全家桶感觉太分散了，Polaris目前体验下来产品集成度比阿里的那套高不少，但是功能特性比阿里的组件还差不少，作为开发者希望能够在一个平台上能够完成整个微服务的治理工作，包括网关，服务注册，限流，熔断等等，这样的话可以不用在不同的平台（组件）切换，很方便的在一个控制台就完成了所有的微服务治理工作。
**How to implement this feature?**

**Additional context**

**Comment by chuntaojun** [comment]
这个后续可以考虑针对网关这一块独立出一个专门的治理模块 UI，目前会先将服务治理相关的规则 spec 适配到 Envoy 以及 Nginx 两个主流网关中
