### ISSUE TITLE
希望增加日志级别动态修改功能

### ISSUE THREAD

**Issue by beretaa** [polarismesh/polaris#1288]
**What is the feature you want to add?**
希望增加日志级别动态修改功能
**Why do you want to add this feature?**
微服务系统下若想调整某个服务某个logger的日志级别比较困难, 只能挨个副本调整,费时费力
想临时放开某个debug日志排查问题比较困难, 只打开单一副本debug信息不够全面
**How to implement this feature?**
1.定时采集各服务副本的loggers和等级,一般情况下一个服务所有副本的loggers配置相同
2.修改logger等级后将事件广播到所有节点
3.需要客户端支持响应logger调整事件, 适配各语言的log框架...  可以优先搞搞Java[手动狗头]
**Additional context**
请参考springboot-admin 的Loggers模块

**Comment by chuntaojun** [comment]
这个sct已适配，主要看相关微服务框架是否做了这个事情，北极星只是一个配置托管中心，负责下发配置，但是配置怎么使用，如何动态生效，这个需要周边微服务框架实现

**Comment by SkyeBeFreeman** [comment]
直接在控制台上更新日志级别即可，相关实现类，com.tencent.cloud.polaris.config.logger.PolarisConfigLoggerApplicationListener

**Comment by beretaa** [comment]
@SkyeBeFreeman 大佬, 这个类和logger包找不到 
![image](https://github.com/polarismesh/polaris/assets/130036897/695c2d5e-eb99-48b6-8dbb-6b3f4260292d)

**Comment by SkyeBeFreeman** [comment]
SCT的话，1.12.1以上的版本支持这个功能。
