### ISSUE TITLE
配置中心建议支持http协议。

### ISSUE THREAD

**Issue by BruceAn1978** [polarismesh/polaris#1319]
**What is the feature you want to add?**
服务发现/注册中心同时支持gRpc和http协议，但是配置中心只支持gRpc单一协议。

**Why do you want to add this feature?**
配置中心也同时支持gRpc和http协议。

**Additional context**
Polaris会以Docker镜像的方式发布至K8S集群环境，集群环境中http协议很好配置，但是tcp协议（gRpc等）的配置非常麻烦，IT也不建议集群内部使用tcp协议，因此需要配置中心支持http协议。

**Comment by chuntaojun** [comment]
请查看 OpenAPI 文档：https://polarismesh.cn/docs/%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3/open_api/

**Comment by chuntaojun** [comment]
<img width="316" alt="Screenshot 2024-01-09 at 9 04 55 PM" src="https://github.com/polarismesh/polaris/assets/23445172/da62a5a7-8e24-4af4-b023-5224c84db4e0">

**Comment by BruceAn1978** [comment]
我指的配置中心支持http协议是在bootstrap.yml中支持http配置，现在yml改为http协议后，按照文档，不知道端口是哪个？尝试了几个端口后，应用启动一直报错。

内置的Polaris Cloud Config组件不支持http协议。

**Comment by chuntaojun** [comment]
SDK 是仅支持 gRPC

**Comment by chuntaojun** [comment]
如果你要 SDK 支持 http 协议，可以向 polaris-java 贡献关于 http 的 server connector 插件

**Comment by BruceAn1978** [comment]
我这是提了一个功能建议，团队如何处理那是团队的决策问题。

首先Server需要支持http协议的配置中心连接能力，同时确定对外暴漏的端口号。
然后spring-cloud-starter-tencent-polaris-config组件需要支持http协议。

**Comment by chuntaojun** [comment]
1、文档这里我们更新下最新描述，8090 是 OpenAPI 端口，可以支持配置中心的相关操作
2、社区不会主动推进 SDK 通过 http 协议和服务端建立通行，如果你们有需求可以根据 SDK 的插件机制执行实现
