### ISSUE TITLE
控制台增删改限流规则偶发不生效

### ISSUE THREAD

**Issue by liuyongde19950808** [polarismesh/polaris#1321]
**Describe the bug**
控制台新增，修改，删除限流规则后，在调用服务时规则没起作用

**To Reproduce**
1.新增限流规则
![image](https://github.com/polarismesh/polaris-sidecar/assets/103579481/7ebf8a05-ae42-4412-961b-f3ab58887f4e)

2.查询限流数据
![image](https://github.com/polarismesh/polaris-sidecar/assets/103579481/407a50c2-7817-4289-878c-5da8986401ba)

3.进入pod上的polaris sidecar容器内curl http://127.0.0.1:15000/config_dump > dump.json，显示并不是最新限流规则数据
![image](https://github.com/polarismesh/polaris-sidecar/assets/103579481/73e0d216-6dde-4ca4-a13e-266dc49bc308)

**Expected behavior**
修改后的限流能生效

**Environment**
- polaris 1.17.9
- k8s-1.28.3

**Additional context**

**Comment by chuntaojun** [comment]
fix in 1.18.0
