### ISSUE TITLE
内部项目接入-腾讯云实例健康检查一直超时导致告警不断（应用功能不受影响，但是会有超时告警）

### ISSUE THREAD

**Issue by xjiahong** [polarismesh/polaris#1330]
我接入了腾讯云的北极星组件，但是有一个健康检查接口一直在报超时，以下是我的腾讯云版本
![image](https://github.com/polarismesh/polaris/assets/19721126/c4b12705-7932-45e0-a1e0-aff660f00fee)
以下是我代码里面的版本
![image](https://github.com/polarismesh/polaris/assets/19721126/6844dd3c-d3cf-4b80-a1a0-4543ea27a72c)
以下是我告警的情况，导致一直告警
![image](https://github.com/polarismesh/polaris/assets/19721126/f4f6b822-e7d0-4aed-8bee-d29d7e269bb7)
接口调用和应用都没有问题，也没有出现过宕机等情况，功能使用不受影响，但是这个健康检查一直出问题

**Comment by xjiahong** [comment]
随便点开一个链路追踪：
![image](https://github.com/polarismesh/polaris/assets/19721126/180e0c6e-65bd-4dbf-8adf-6fc4d7b7675e)
希望支持团队可以拉个群支持一下，使用的项目是腾讯内部项目

**Comment by xjiahong** [comment]
现在用APM屏蔽了健康检查上报来解决的，具体原因未知

**Comment by chuntaojun** [comment]
这个 grpc 接口北极星没有去实现，建议 apm 看下怎么关闭这个接口的监控上报

**Comment by xjiahong** [comment]
已经处理了，屏蔽了这个接口的apm上报



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月4日(周一) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [polarismesh/polaris] 内部项目接入-腾讯云实例健康检查一直超时导致告警不断（应用功能不受影响，但是会有超时告警） (Issue #1330)




 
这个 grpc 接口北极星没有去实现，建议 apm 看下怎么关闭这个接口的监控上报

**Comment by chuntaojun** [comment]
这个原因和北极星没有关系的，北极星并未提供这个接口，北极星 SDK 本身也没有提供 gRPC 的 health.Watch 来检查北极星SDK和北极星服务端之间的健康检查，建议看下 kratos 这里是不是有开启这个 gRPC 的 health 机制

**Comment by xjiahong** [comment]
好的感谢，我这边排查下kratos的
