### ISSUE TITLE
standalone 生产环境使用可行性和问题

### ISSUE THREAD

**Issue by liukaifei** [polarismesh/polaris#1365]
我的系统规模很小，20几个服务，2-3台服务器，为了方便实施部署（线下系统），请问standalone版本用于生产环境是否可行，可能会存在什么问题？针对类似小规模服务，使用polarismesh有什么建议？谢谢！

**Comment by chuntaojun** [comment]
standalone 生产的话，其实就面临单节点风险，你们需要评估下是否可以忍受，当北极星不可用时，SDK侧会根据上一次的缓存支持业务完成请求，但是如果业务也重启了，但是北极星还没恢复，那就会有问题了

**Comment by liukaifei** [comment]
> standalone 生产的话，其实就面临单节点风险，你们需要评估下是否可以忍受，当北极星不可用时，SDK侧会根据上一次的缓存支持业务完成请求，但是如果业务也重启了，但是北极星还没恢复，那就会有问题了

收到，谢谢！
