### ISSUE TITLE
Add shell operation ability to polaris

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#150]
**What is the feature you want to add?**

Allows users to interact with polaris through shell commands, for example
1. View service or service instance
2. View service governance rules information
3. Do some operation and maintenance capabilities for polaris, such as forcing update of internal cache, restarting apisever, etc.

**Why do you want to add this feature?**

Provide command line interaction capabilities for Polaris, and provide another way of operation and maintenance capabilities and experience

**How to implement this feature?**

**Additional context**

**Comment by li-xiao-shuang** [comment]
我可以尝试搞下这个任务，第一版可以先实现一些查询命令 不知道polaris是否有一些openapi?

**Comment by chuntaojun** [comment]
see https://github.com/polaris-contrib/polarisctl
