### ISSUE TITLE
Unable to clean up the service cache whose namesapce has been deleted, causing a memory leak 

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#157]
**What is the feature you want to add?**

Unable to clean up the service cache whose namesapce has been deleted, causing a memory leak 

**Why do you want to add this feature?**

causing a memory leak 

**How to implement this feature?**

> 中文

前置约束
1. 删除Namespace、Service资源时，必须保证其下面的子资源都已经被清理才能执行删除，比如删除Namespace时，必须保证当前Namespace下已经没有任何Service了才可以删除Namespace

其中一种修复思路
1. ServiceCache是负责刷新service的数据
2. 可以在ServiceCache每次Update时，拉取一下Namespace列表，然后和ServiceCache的names缓存做一下数据对账，清理掉脏数据

> English

Pre-constraint
1. When deleting Namespace and Service resources, you must ensure that the sub-resources below have been cleaned up before you can delete it. For example, when deleting a Namespace, you must ensure that there is no Service under the current Namespace before you can delete the Namespace.

One of the repair ideas
1. ServiceCache is responsible for refreshing service data
2. You can pull up the Namespace list every time ServiceCache is updated, and then do a data reconciliation with the names cache of ServiceCache to clean up dirty data

**Additional context**

**Comment by liu-song** [comment]
I will try to fix it.
