### ISSUE TITLE
Helmchart support with default namespace

### ISSUE THREAD

**Issue by yagrxu** [polarismesh/polaris#161]
What is the feature you want to add?
I would like to deploy the cluster in K8s with helmchart, and also with a default namespace like "polarishmesh"

Why do you want to add this feature?

helmchart provide more features to tweak with deployment variables
a namespace other than "default" is more appropriate for registry component

**How to implement this feature?**

**Additional context**

**Comment by zhangzerui20** [comment]
I will solve it.
