### ISSUE TITLE
Failed to build polaris on macOS

### ISSUE THREAD

**Issue by GuangmingLuo** [polarismesh/polaris#218]
**Describe the bug**
Failed to build polaris on macOS

**To Reproduce**
1. chmod +x build.sh
2. ./build.sh 
./build.sh: line 5: realpath: command not found
usage: dirname string [...]

**Expected behavior**
After built, one can see 'polaris-server-release_${version}.tar.gz' package from the list.

**Environment**
- Version: latest
- OS: macOS Monterey

**Comment by chuntaojun** [comment]
tks，we will fix it

**Comment by chuntaojun** [comment]
- you can execute the following commands under mac first, so that you can use realpath commands on mac

```bash
brew install coreutils
```

- In the follow-up, we will look at how to optimize the build script so that users can perform the build actions as smoothly as possible.

**Comment by GuangmingLuo** [comment]
> * you can execute the following commands under mac first, so that you can use realpath commands on mac
> 
> ```shell
> brew install coreutils
> ```
> 
> * In the follow-up, we will look at how to optimize the build script so that users can perform the build actions as smoothly as possible.

OK 了

**Comment by andrewshan** [comment]
pls optimize the document to make the prefix operation more clear

**Comment by chuntaojun** [comment]
ok
