### ISSUE TITLE
mac环境下 build.sh realpath 无对应命令

### ISSUE THREAD

**Issue by xiaohongxiedaima** [polarismesh/polaris#25]
realpath: command not found
shell 新增函数可以解决
```
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
```

判断环境变了的写法也有问题
```
if [ -n "$GOOS" ] && [ -n "$GOARCH" ]
then
        folder_name="polaris-server-release_${version}.${GOOS}.${GOARCH}"
fi
```

**Comment by chenhengqi** [comment]
`realpath` is part of GNU coreutils.

`brew install coreutils` should work.

**Comment by xiaohongxiedaima** [comment]
when the GOOS and GOARCH environment variable do not exist

the build.sh script echo `polaris-server-release_v1.0.1..` 

`if [ -n $GOOS ] && [ -n $GOARCH ]` should be replace by `if [ -n "$GOOS" ] && [ -n "$GOARCH" ]`
