### ISSUE TITLE
./tool/p.sh执行后，没有任何输出

### ISSUE THREAD

**Issue by fineday009** [polarismesh/polaris#26]
`❯ ./tool/install.sh
++ pwd
+ curpath=/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1..
+ '[' . == / ']'
++ pwd
++ dirname ./tool/install.sh
+ dir=/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1.././tool
+ cd /Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1.././tool/..
++ pwd
+ workdir=/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1..
+ source tool/include
++ server_name=polaris-server
++ cmdline='./polaris-server start'
+ chmod 755 tool/check.sh tool/install.sh tool/p.sh tool/reload.sh tool/start.sh tool/stop.sh tool/uninstall.sh polaris-server
+ item='/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1../tool/check.sh >>/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1../log/check.log 2>&1'
++ crontab -l
++ grep '/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1../tool/check.sh >>/Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1../log/check.log 2>&1'
++ grep -v '#'
++ wc -l
crontab: no crontab for iceewei
+ exist='       0'
+ '[' '       0' == 0 ']'
+ cd /Users/iceewei/projects/go_proj/src/github.com/polaris/polaris-server-release_v1.0.1..
❯ 
❯ ./tool/p.sh

❯ 
`

**Comment by andrewshan** [comment]
hello, can you put the config file polaris.yaml here? it seems that the server startup fail due to the wrong database params

**Comment by andrewshan** [comment]
we have released 1.2.0 version, big improvement to installation scripts, pls have a try

**Comment by xiaohongxiedaima** [comment]
> hello, can you put the config file polaris.yaml here? it seems that the server startup fail due to the wrong database params

there is no `crontab` command on a non-root account in osx

`crontab: no crontab for iceewei`

**Comment by chuntaojun** [comment]
If the current user has not configured the crontab task, the output of crontab -l is different from that of Linux. The MAC OS does not support crontab, I will fix this output problem
