### ISSUE TITLE
k8s use docker hub image polaris-console error

### ISSUE THREAD

**Issue by tsingsun** [polarismesh/polaris#275]
**Describe the bug**

在Mac 单机k8s,使用polaris-console: v1.3.1出错
而如果改使用 ccr.ccs.tencentyun.com/polaris_mesh/polaris-console:latest 即是正常的

**Expected behavior**
通过docker hub的镜像能正常搭建polaris环境

**Environment**
- Version: v1.5.0
- OS: mac docker desktop v4.2 with kubernetes

**Comment by andrewshan** [comment]
有具体的错误信息么？

**Comment by tsingsun** [comment]
k8s日志polaris-console stdout 输出只有一行
```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

**Comment by andrewshan** [comment]
试着换一下这个镜像：polarismesh/polaris-console:v1.3.2

**Comment by tsingsun** [comment]
多谢~这个镜像可以.chrome下正常
