### ISSUE TITLE
The exported interface type needs to be annotated, the annotations here are not standardized

### ISSUE THREAD

**Issue by daheige** [polarismesh/polaris#28]
https://github.com/polarismesh/polaris/blob/b963e26fafe9958e868971caf38f9b5cb3a3c619/store/api.go#L72

**Comment by daheige** [comment]
``` go
/**
 * @brief 配置
 */
type Config struct {
```
As an open source project, can the code specification and code style be dealt with first? This writing method is completely inconsistent with the go code specification. At first glance, it is generated in batches with tools, but it must also follow the go code specification principle. This is the basic Common sense.

**Comment by daheige** [comment]
As mentioned above, please pay attention to the code specification. Please do not mix Chinese and English code comments in it, which is unprofessional

**Comment by andrewshan** [comment]
OK, we will fixed them ,thanks for you suggestion
