### ISSUE TITLE
instanceCache 以实例数是否相同做为全量对账的条件是否过于粗糙？

### ISSUE THREAD

**Issue by shichaoyuan** [polarismesh/polaris#294]
instanceCache 以实例数是否相同做为全量对账的条件是否过于粗糙？

```
func (ic *instanceCache) checkAll() {
	curTimeSec := time.Now().Unix()
	if curTimeSec-ic.lastCheckAllTime < checkAllIntervalSec {
		return
	}
	defer func() {
		ic.lastCheckAllTime = curTimeSec
	}()
	count, err := ic.storage.GetInstancesCount()
	if err != nil {
		log.CacheScope().Errorf("[Cache][Instance] get instance count from storage err: %s", err.Error())
		return
	}
	if ic.instanceCount == int64(count) {
		return
	}
	log.CacheScope().Infof(
		"[Cache][Instance] instance count not match, expect %d, actual %d, fallback to load all",
		count, ic.instanceCount)
	ic.lastMtime = 0
}

```

**Comment by andrewshan** [comment]
北极星保证缓存与数据库的一致性主要是基于以下手段来保证的：
1. 数据写入数据库时，每个记录都会带入数据库的当前时间。
2. 缓存会通过定时方式每秒去获取离上一次更新的时间戳之后的数据，并且为了防止数据库时间倒退，每次拉取都会相对最新的时间戳往前倒退4s进行拉取。
基于上述2个逻辑，基本不会有数据的丢失。

这个兜底逻辑其实是为了防止出现时间大面积倒退的极端情况下，进行一个兜底，因为假如发生大面积倒退，基本上都会出现数据的数量不一致，这里做的一个按数量兜底，也是守住这一个防线。

**Comment by shichaoyuan** [comment]
> 北极星保证缓存与数据库的一致性主要是基于以下手段来保证的：
> 
> 1. 数据写入数据库时，每个记录都会带入数据库的当前时间。
> 2. 缓存会通过定时方式每秒去获取离上一次更新的时间戳之后的数据，并且为了防止数据库时间倒退，每次拉取都会相对最新的时间戳往前倒退4s进行拉取。
>    基于上述2个逻辑，在腾讯内部运营了这么久，基本不会有数据的丢失。
> 
> 这个兜底逻辑其实是为了防止出现时间大面积倒退的极端情况下，进行一个兜底，因为假如发生大面积倒退，从业务系统持续运行的过程中，肯定上都会因为上下线或者元数据的变更，出现数据的数量不一致，这里做的一个按数量兜底，也是守住这一个防线。

嗯 这个增量更新的逻辑是很完善了。

还想再了解一下你们内部有遇到过这种极端情况么？

**Comment by andrewshan** [comment]
> > 北极星保证缓存与数据库的一致性主要是基于以下手段来保证的：
> > 
> > 1. 数据写入数据库时，每个记录都会带入数据库的当前时间。
> > 2. 缓存会通过定时方式每秒去获取离上一次更新的时间戳之后的数据，并且为了防止数据库时间倒退，每次拉取都会相对最新的时间戳往前倒退4s进行拉取。
> >    基于上述2个逻辑，在腾讯内部运营了这么久，基本不会有数据的丢失。
> > 
> > 这个兜底逻辑其实是为了防止出现时间大面积倒退的极端情况下，进行一个兜底，因为假如发生大面积倒退，从业务系统持续运行的过程中，肯定上都会因为上下线或者元数据的变更，出现数据的数量不一致，这里做的一个按数量兜底，也是守住这一个防线。
> 
> 嗯 这个增量更新的逻辑是很完善了。
> 
> 还想再了解一下你们内部有遇到过这种极端情况么？

运营了3年了，还没有遇到过
