### ISSUE TITLE
控制台密码多少

### ISSUE THREAD

**Issue by cn-ygf** [polarismesh/polaris#330]
http://127.0.0.1:8080/#/login
默认账号密码文档不写？

**Comment by chuntaojun** [comment]
文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0

**Comment by cn-ygf** [comment]
> 文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0


提示
not found user

**Comment by chuntaojun** [comment]
> > 文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0
> 
> 提示 not found user

你的存储使用的是mysql、还是单机的boltdb呢？

**Comment by chuntaojun** [comment]
> > 文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0
> 
> 提示 not found user

建议先使用mysql存储来体验鉴权，鉴权能力在boltdb存储下会在1.7.1彻底修复适配

**Comment by cn-ygf** [comment]
> > > 文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0
> > 
> > 
> > 提示 not found user
> 
> 建议先使用mysql存储来体验鉴权，鉴权能力在boltdb存储下会在1.7.1彻底修复适配

单机默认的boltdb
现在改成mysql 表结构怎么导进去？

**Comment by cn-ygf** [comment]
> > > 文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0
> > 
> > 
> > 提示 not found user
> 
> 建议先使用mysql存储来体验鉴权，鉴权能力在boltdb存储下会在1.7.1彻底修复适配

好的 ，感谢，我去集群版下个sql文件

**Comment by chuntaojun** [comment]
> > 文档中已经补充了：https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%89%B4%E6%9D%83%E6%8E%A7%E5%88%B6/%E6%A6%82%E8%BF%B0.html#%E6%A6%82%E8%BF%B0
> 
> 提示 not found user

这里现在体验还有什么问题吗
