### ISSUE TITLE
在控制台的配置中心创建配置异常

### ISSUE THREAD

**Issue by 1005281342** [polarismesh/polaris#337]
**Describe the bug**
使用polaris账号，根据[文档](https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83/%E4%BD%BF%E7%94%A8%E6%8E%A7%E5%88%B6%E5%8F%B0.html#%E4%BD%BF%E7%94%A8%E6%8E%A7%E5%88%B6%E5%8F%B0)在控制台的配置中心创建配置异常

**To Reproduce**
新建配置文件组，响应看起来是成功的，但是仍然是再弹框这，继续点了一次
<img width="1553" alt="image-20220405170834915" src="https://user-images.githubusercontent.com/29853262/161721638-b5aa13da-08a2-46d6-8dae-74a08b3701e4.png">

刷新了下页面，看起来没有新建成功
<img width="1562" alt="image-20220405170929662" src="https://user-images.githubusercontent.com/29853262/161721759-388b80c8-a19f-4671-8107-9aacbec2356e.png">

**Expected behavior**
希望像[文档](https://polarismesh.cn/zh/doc/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83/%E4%BD%BF%E7%94%A8%E6%8E%A7%E5%88%B6%E5%8F%B0.html#%E4%BD%BF%E7%94%A8%E6%8E%A7%E5%88%B6%E5%8F%B0)那样创建成功

**Environment**
- Version: polaris-standalone-release_v1.7.0.darwin.amd64 https://github.com/polarismesh/polaris/releases/download/v1.7.0/polaris-standalone-release_v1.7.0.darwin.amd64.zip
- OS: macOS Monterey 12.2.1

**Additional context**

**Comment by chuntaojun** [comment]
这里配置目前需要搭配mysql进行使用，单机版本的问题，会在1.7.1进行修复
