### ISSUE TITLE
配置中心支持鉴权

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#338]
**What is the feature you want to add?**

1. 针对配置中心的控制台接口、客户端接口分别鉴权
2. 前端需要参考开启鉴权后，服务信息编辑、修改页面涉及鉴权的功能需要迁移至配置模块

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris/issues/472

**Comment by yuezhongtao** [comment]
[WeOpen Star]I would like to help

**Comment by chuntaojun** [comment]
- 需要完善针对 config_group 创建时的相关信息收集，然后放入 AcquireContext 中
  - config_group 的 name
  - config_group 所在的 namespace
- 需要提供根据 config_group 唯一ID获取对应 config_group 实例的方法
- 需要为 config_group 新增 Editable 属性，用于前端判断该资源是否可以编辑
- 需要参考 ResourceHook 的设计，完善针对 config_group 创建、删除的相关后置处理
  - 参考 namespace 的 ResourceHook 流程，或者在 Service 下的 ResourceHook 流程
  - 某个用户创建 config_group 时，需要将可以操作的 user_id 以及 group_id，更新他们的默认策略信息
- GetStrategies 方法需要补充关于 配置分组 的信息展示
- GetPrincipalResources 需要补充关于 配置分组 的信息展示

- 需要补充相关单元测试
