### ISSUE TITLE
北极星内部事件中心机制优化

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#342]
**What is the feature you want to add?**

1. 一个统一的事件中心
2. 每种事件有自己单独的publisher，每种事件的产生、发布、消费互不影响
3. 将原本的服务事件插件与该事件中心组合，建立一个Listener，该Listener的逻辑代替原本discoverevent的逻辑
4. 后续基于此事件中心，实现配置相关事件的暴露、持久化日志等操作

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by alexwanglei** [comment]
assign me

**Comment by chuntaojun** [comment]
> assign me

可以在这个 issue 下面回复下预想的设计方案～

**Comment by alexwanglei** [comment]
初步想法是实现一个pub/sub的事件总线，不同类型的Event通过Topic进行分类。事件订阅者根据topic订阅事件，同时将自己的eventQueue添加到topic下的队列列表中，事件发布者发布事件，把事件广播到topic下的事件队列列表中。事件订阅者（Discoverevent插件）可以自行消费其eventQueue来记录事件。
```go
type Event struct {
       Topic string
       Data interface{}
}

type EventQueue chan Event

type EventCenter struct {
	topicEventQueues map[string][]EventQueue
}

func (ec *EventCenter) Publish(event Event) {
	for _, eq := ec.topicEventQueues[event.Topic] {
		eq <- event
	}
}

func (ec *EventCenter) Subscribe(topic string, eventQueue EventQueue) {
	ec.topicEventQueues[topic] = append(ec.topicEventQueues[topic], eventQueue)
}
```

**Comment by chuntaojun** [comment]
> 初步想法是实现一个pub/sub的事件总线，不同类型的Event通过Topic进行分类。事件订阅者根据topic订阅事件，同时将自己的eventQueue添加到topic下的队列列表中，事件发布者发布事件，把事件广播到topic下的事件队列列表中。事件订阅者（Discoverevent插件）可以自行消费其eventQueue来记录事件。
> 
> ```go
> type Event struct {
>        Topic string
>        Data interface{}
> }
> 
> type EventQueue chan Event
> 
> type EventCenter struct {
> 	topicEventQueues map[string][]EventQueue
> }
> 
> func (ec *EventCenter) Publish(event Event) {
> 	for _, eq := ec.topicEventQueues[event.Topic] {
> 		eq <- event
> 	}
> }
> 
> func (ec *EventCenter) Subscribe(topic string, eventQueue EventQueue) {
> 	ec.topicEventQueues[topic] = append(ec.topicEventQueues[topic], eventQueue)
> }
> ```

是不是可以考虑升级下 go 的版本，把范型用起来？ @andrewshan  @daheige  怎么看

**Comment by chuntaojun** [comment]
```golang
func (ec *EventCenter) Subscribe(topic string, eventQueue EventQueue) {
	ec.topicEventQueues[topic] = append(ec.topicEventQueues[topic], eventQueue)
}
```

这个直接改为注册一个函数会不会好一点？也不需要关心chan的关闭销毁，如果要用chan，那应该是 Subscribe 的时候返回一个只读 chan

**Comment by daheige** [comment]
https://github.com/daheige/workpool


Take a look at this. Add the task to the pool chan and schedule the task execution through the workpool



------------------ 原始邮件 ------------------
发件人: liaochuntao ***@***.***&gt;
发送时间: 2022年11月1日 17:13
收件人: polarismesh/polaris ***@***.***&gt;
抄送: heige ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [polarismesh/polaris] 北极星内部事件中心机制优化 (Issue #342)





 func (ec *EventCenter) Subscribe(topic string, eventQueue EventQueue) { ec.topicEventQueues[topic] = append(ec.topicEventQueues[topic], eventQueue) }
 
这个直接改为注册一个函数会不会好一点？也不需要关心chan的关闭销毁，如果要用chan，那应该是 Subscribe 的时候返回一个只读 chan

**Comment by daheige** [comment]
> > 初步想法是实现一个pub/sub的事件总线，不同类型的Event通过Topic进行分类。事件订阅者根据topic订阅事件，同时将自己的eventQueue添加到topic下的队列列表中，事件发布者发布事件，把事件广播到topic下的事件队列列表中。事件订阅者（Discoverevent插件）可以自行消费其eventQueue来记录事件。
> > ```go
> > type Event struct {
> >        Topic string
> >        Data interface{}
> > }
> > 
> > type EventQueue chan Event
> > 
> > type EventCenter struct {
> > 	topicEventQueues map[string][]EventQueue
> > }
> > 
> > func (ec *EventCenter) Publish(event Event) {
> > 	for _, eq := ec.topicEventQueues[event.Topic] {
> > 		eq <- event
> > 	}
> > }
> > 
> > func (ec *EventCenter) Subscribe(topic string, eventQueue EventQueue) {
> > 	ec.topicEventQueues[topic] = append(ec.topicEventQueues[topic], eventQueue)
> > }
> > ```
> 
> 是不是可以考虑升级下 go 的版本，把范型用起来？ @andrewshan @daheige 怎么看

For this use of go 1.18.x+ generic design, it may be better, but the current data uses the type of interface {}, there is no big problem.

**Comment by daheige** [comment]
> > 初步想法是实现一个pub/sub的事件总线，不同类型的Event通过Topic进行分类。事件订阅者根据topic订阅事件，同时将自己的eventQueue添加到topic下的队列列表中，事件发布者发布事件，把事件广播到topic下的事件队列列表中。事件订阅者（Discoverevent插件）可以自行消费其eventQueue来记录事件。
> > ```go
> > type Event struct {
> >        Topic string
> >        Data interface{}
> > }
> > 
> > type EventQueue chan Event
> > 
> > type EventCenter struct {
> > 	topicEventQueues map[string][]EventQueue
> > }
> > 
> > func (ec *EventCenter) Publish(event Event) {
> > 	for _, eq := ec.topicEventQueues[event.Topic] {
> > 		eq <- event
> > 	}
> > }
> > 
> > func (ec *EventCenter) Subscribe(topic string, eventQueue EventQueue) {
> > 	ec.topicEventQueues[topic] = append(ec.topicEventQueues[topic], eventQueue)
> > }
> > ```
> 
> 是不是可以考虑升级下 go 的版本，把范型用起来？ @andrewshan @daheige 怎么看
@chuntaojun For pub/sub design, I strongly recommend this package: https://github.com/go-god/broker , this package is a pub/sub model, supports redis, kafka, pulsar mechanism, and of course can be extended based on local memory way to implement this broker to satisfy the pub/sub of Polaris

**Comment by chuntaojun** [comment]
> 我尝试使用泛型来定义Event[T]，但是如果EventHub要持有Event[T]或者操作Event[T]，EventHub也必须定义成泛型EventHub[T]。EventHub不应该跟具体事件类型关联，应该是一个全局单例的对象，因此就无法包含泛型对象以及提供泛型方法。泛型的使用这方面我之前没有经验，不知道这个问题改怎么解决？目前只实现了非泛型的一版，还请大佬们帮忙看看。 @chuntaojun @daheige

没办法在 Publish 上绑定 泛型 看来？

**Comment by chuntaojun** [comment]
> 我尝试使用泛型来定义Event[T]，但是如果EventHub要持有Event[T]或者操作Event[T]，EventHub也必须定义成泛型EventHub[T]。EventHub不应该跟具体事件类型关联，应该是一个全局单例的对象，因此就无法包含泛型对象以及提供泛型方法。泛型的使用这方面我之前没有经验，不知道这个问题改怎么解决？目前只实现了非泛型的一版，还请大佬们帮忙看看。 @chuntaojun @daheige

那就先不考虑泛型吧

**Comment by chuntaojun** [comment]
> > > 我尝试使用泛型来定义Event[T]，但是如果EventHub要持有Event[T]或者操作Event[T]，EventHub也必须定义成泛型EventHub[T]。EventHub不应该跟具体事件类型关联，应该是一个全局单例的对象，因此就无法包含泛型对象以及提供泛型方法。泛型的使用这方面我之前没有经验，不知道这个问题改怎么解决？目前只实现了非泛型的一版，还请大佬们帮忙看看。 @chuntaojun @daheige
> > 
> > 
> > 没办法在 Publish 上绑定 泛型 看来？
> 
> Publish如果是一个函数是可以的，如果是方法则方法的接收器也必须是泛型

那如果搞成一个函数呢？在 Publish 里面调用 eventHub ？

**Comment by alexwanglei** [comment]
> 

这样感觉也绕不开，只要eventHub持有泛型对象，eventHub就需要定义泛型约束。Event[T]总是要临时存储在类似Channel[T]这样的容器中，eventHub似乎没办法拥有包含不同类型的Channel[T]的成员

**Comment by chuntaojun** [comment]
> > 
> 
> 这样感觉也绕不开，只要eventHub持有泛型对象，eventHub就需要定义泛型约束。Event[T]总是要临时存储在类似Channel[T]这样的容器中，eventHub似乎没办法拥有包含不同类型的Channel[T]的成员

那就先不考虑了，就先 interface{} 处理吧

**Comment by daheige** [comment]
> 

同意

**Comment by edocevol** [comment]
正在做的 plugin 机制也可以实现将事件往外分发~
