### ISSUE TITLE
支持动态修改server的日志级别参数

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#346]
**What is the feature you want to add?**

- 可以通过open-api修改server中某个logger的日志级别

**Why do you want to add this feature?**

- 现有的修改日志级别，需要修改配置并重启server，对于现场需要开启debug级别日志排查问题不友好

**How to implement this feature?**

- server的日志管理模块，提供 SetLevel(scopeName, logLevel) 来针对某个 logger 设置 level
- 提供 open-api 进行设置
- 对于该 open-api 添加鉴权操作

**Additional context**

**Comment by city55238** [comment]
我可以尝试解决这个issue吗
