### ISSUE TITLE
运维相关接口需要纳入鉴权管理体系

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#349]
Discussed in https://github.com/polarismesh/polaris/discussions/357

**What is the feature you want to add?**

- 运维接口涉及一些高危操作，在鉴权开启时，只能允许主账户进行操作

**Why do you want to add this feature?**

- 在鉴权开启时，避免此类高危接口允许被匿名调用

**How to implement this feature?**

**Additional context**

**Comment by shichaoyuan** [comment]
assigne me

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris/discussions/357
