### ISSUE TITLE
可以提供docker搭建北极星的文件嘛

### ISSUE THREAD

**Issue by livk-cloud** [polarismesh/polaris#370]

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris/blob/main/Dockerfile，这个是定义的Dockerfile，然后设置volume映射，把 polaris-server.yaml 文件映射到容器内的 /root 路径下

**Comment by livk-cloud** [comment]
@chuntaojun 好的，我试试

**Comment by chuntaojun** [comment]
在deploy/standalone下提供了构建单机docker镜像的能力了～
