### ISSUE TITLE
优化polaris-server的服务注册发现性能瓶颈

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#379]
**What is the feature you want to add?**

#### 针对服务发现

- 针对服务发现接口发起gRPC协议的请求压测
- 服务发现接口的QPS结果，与服务下实例数量成反比
- 通过golang的pprof分析得到的火焰图，得知CPU主要消耗在proto.Marshal中，并且调用了pb.sizePointerSlow

**Why do you want to add this feature?**

#### 针对服务发现

- 针对服务发现接口的protobuf.Marshal做一些hack优化

**How to implement this feature?**

#### 针对服务发现

- 针对 protobuf.Marshal 的结果根据 type.namespace.service + revision 信息进行 cache 缓存
  - 需要遵循LRU机制，避免内存撑爆
  - 需要尽可能避免由于cache更新所带来的锁冲突问题

**Additional context**

**Comment by shichaoyuan** [comment]
有个疑问，大部分情况服务发现的响应应该都是 nochange，理论上序列化的成本应该不高，而在变更的阶段加上一个缓存感觉作用不是很大。对于全量数据比较大的问题，增量机制可能是一个比较好的选择。

**Comment by chuntaojun** [comment]
> 有个疑问，大部分情况服务发现的响应应该都是 nochange，理论上序列化的成本应该不高，而在变更的阶段加上一个缓存感觉作用不是很大。对于全量数据比较大的问题，增量机制可能是一个比较好的选择。

NoChange只是针对单个客户端和server之间的数据对比，需要解决的时同时有大量的客户端过来拉同一个服务实例，减少序列化带来的CPU开销

**Comment by chuntaojun** [comment]
增量机制只是解决单个客户端到server之间的数据推送量，但是如果大量的客户端第一次同时拉取某个服务下的实例，增量机制并不能解决这个问题，而且增量机制必定还需要一定的兜底之际，比如超过多少个版本之后，只能拉取全量做兜底保护

**Comment by shichaoyuan** [comment]
恩 这个场景，缓存确实很有必要。
