### ISSUE TITLE
docker带配置文件的polaris-server脚本已经合并，能发一版用吗？

### ISSUE THREAD

**Issue by huyuanxin** [polarismesh/polaris#390]

**Comment by chuntaojun** [comment]
会在下一个版本发布的时候进行处理

**Comment by chuntaojun** [comment]
already push

**Comment by chuntaojun** [comment]
https://hub.docker.com/repository/docker/polarismesh/polaris-server-standalone

**Comment by houseme** [comment]
https://hub.docker.com/r/polarismesh/polaris-server-standalone
