### ISSUE TITLE
polaris-server 服务注册panic

### ISSUE THREAD

**Issue by zhengheng7913** [polarismesh/polaris#414]
**Describe the bug**
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/39586541/172022773-58aac9a7-c696-4706-bd7c-b48f9219098e.png">

服务注册时有几率出现空指针导致服务panic

**To Reproduce**
polaris-go v.1.1.0版本注册服务

**Expected behavior**
服务状态应正常维护，不会导致panic

**Environment**
- Version:v1.8.0
- OS: K8S

**Comment by chuntaojun** [comment]
看下配置有没有更新成1.8.0对应的polaris-server.yaml

**Comment by zhengheng7913** [comment]
配置文件重新下发后正常了，谢谢协助
