### ISSUE TITLE
Support ARM 64-bit architectures

### ISSUE THREAD

**Issue by onecer** [polarismesh/polaris#42]
**What is the feature you want to add?**

- Support ARM 64-bit architectures

**Why do you want to add this feature?**

- Support ARM 64-bit architectures

**How to implement this feature?**

- Cross-platform build

**Additional context**

When Huawei is sanctioned. We have some services run on the Huawei Kunpeng ARM64 arch platform to support Huawei. Maybe  someone else also need this.

**Comment by andrewshan** [comment]
we have already supported arm64 bit for mac.
will you contribute an arm64 version for linux as well?

**Comment by andrewshan** [comment]
@onecer hello, do you have time to do this feature? any advise can let us know, thanks

**Comment by andrewshan** [comment]
1. 实现思路，改一下流水线脚本，增加linux arm64的编译选项
2. 编译时候假如出现编译失败，根据编译的失败问题具体看
