### ISSUE TITLE
polaris建库sql支持utf8bm4

### ISSUE THREAD

**Issue by davionchen** [polarismesh/polaris#430]
**What is the feature you want to add?**
建库sql是基于utf-8，需要支持utf8bm4

**Comment by HIPIAOYI** [comment]
> **What is the feature you want to add?** 建库sql是基于utf-8，需要支持utf8bm4

建库sql脚本polaris_server.sql用的utf-8，提供一个脚本，基于polaris_server.sql，生成polaris_server_utf8bm4.sql 使用utf8bm4  ，是否可行？

**Comment by andrewshan** [comment]
在MySQL的官方标准中，utf8mb4是更推荐的utf8的实现，utf8反而并非标准的utf8实现，建议这边直接修改当前polaris_server.sql，将编码改成utf8mb4

**Comment by houseme** [comment]
> > **What is the feature you want to add?** 建库sql是基于utf-8，需要支持utf8bm4
> 
> 建库sql脚本polaris_server.sql用的utf-8，提供一个脚本，基于polaris_server.sql，生成polaris_server_utf8bm4.sql 使用utf8bm4 ，是否可行？

[SQL](https://github.com/polarismesh/polaris/pull/441) https://github.com/polarismesh/polaris/pull/441 已经准备好了，你提一个pr吧
