### ISSUE TITLE
polaris-server日志打印，按天归档

### ISSUE THREAD

**Issue by davionchen** [polarismesh/polaris#431]
**What is the feature you want to add?**

polaris-server日志打印，按天归档。

**Why do you want to add this feature?**

1、便于生产归档。
2、部分日志没有切割，比如polaris-history， discover-statis，需要完善

**Comment by awdela02** [comment]
https://github.com/natefinch/lumberjack/issues/17

**Comment by awdela02** [comment]
https://github.com/natefinch/lumberjack/issues/17
