### ISSUE TITLE
能否提供一种方法，让所有polaris的用户都能够在特定namespace下创建service资源

### ISSUE THREAD

**Issue by magederek** [polarismesh/polaris#435]
**What is the feature you want to add?**
能否提供一种方法，让所有polaris的用户都能够在特定namespace下创建service资源

**Why do you want to add this feature?**
**前提**：polaris开启了用户权限控制（Auth）功能
**背**景：我们会建立一些公开（public）的namespace，例如Development、Production，在开启了Auth的情况下，需要增加一个用户组，把所有用户添加到这个用户组中，在用户组的用户才能够在public的namespace下创建service。但是，用户数量是会变化的，新增用户时，如果每次都要管理员操作一下，添加新用户到这个用户组，整个过程会比较繁琐，效率较低。因此，希望有一种更高效率的方式，既能保留使用用户权限控制，也能添加公开的namespace。

**How to implement this feature?**
当前能想到有两个方法：
- **方法一**： 在用户组添加用户列表时，提供一个“所有用户”的选项，这个选项能够自动关联所有的已创建用户，新用户添加后也会自动被加入到这个用户组中，管理员无需额外操作
- **方法二**：为某些特定资源，比如具体的某一个namespace，可以单独设置为公开（public），此时这个特定资源不会再收到权限控制的束缚，当然其里面的子资源还是会收到权限控制的

**Comment by chuntaojun** [comment]
当资源没有关联任何一个策略时，认为该资源是可以被任何人所操作的资源

**Comment by magederek** [comment]
> 可以这样子操作
> 
> * 用户A创建出一个Namespace
> * 点击Namespace的高级设置
> * 在资源的高级设置中的用户列表，将A用户移除，即为将该Namespace设置为公开

那是否可以认为，这个是一个前端优化功能：
1. 在前端使用用户更易于理解的方式，实现这个操作流程
2. 可以有一个标签来提示用户，某种资源是公开的
