### ISSUE TITLE
ERR-1006(SERVER_USER_ERROR), server error 400141: heartbeat on disabled instance

### ISSUE THREAD

**Issue by SkyeBeFreeman** [polarismesh/polaris#438]
https://github.com/Tencent/spring-cloud-tencent/issues/233

**Comment by chuntaojun** [comment]
根据用户的日志定位问题是，在boltdb存储下，instance cache的定时更新任务被挂起了一段时间，导致数据无法正确更新healthcheck的cache层，但是无法复现这个case

**Comment by chuntaojun** [comment]
后续持续跟进处理看下
