### ISSUE TITLE
Who is Using Polaris（谁在使用北极星）

### ISSUE THREAD

**Issue by awdela02** [polarismesh/polaris#439]
公司：腾讯
产品：内部公共服务平台
阶段：生产，200+服务，1000+实例节点
建议：熔断机制更加完善 线上经常会有pod挂掉但是北极星还没有摘掉的情况

**Comment by chuntaojun** [comment]
pls write here：https://github.com/polarismesh/polaris/issues/233

**Comment by andrewshan** [comment]
> 公司：腾讯 产品：内部公共服务平台 阶段：生产，200+服务，1000+实例节点 建议：熔断机制更加完善 线上经常会有pod挂掉但是北极星还没有摘掉的情况

这个会完善，计划会在熔断恢复时候，不会在放量OK后立刻恢复，而是慢慢调整阈值的方式去试探恢复
