### ISSUE TITLE
Just a question, can I use envoy and the xdsv3 server to build a L7 api gateway?

### ISSUE THREAD

**Issue by jxskiss** [polarismesh/polaris#451]
As the title says, can I use envoy and the xdsv3 server to build a L7 api gateway?
The listeners and routes be configured through polaris, and service discovery served by polaris.

**Comment by chuntaojun** [comment]
yes，use envoy and the xdsv3 server to build a L7 api gateway it's ok， polaris-server provider xds-v3 protocol
