### ISSUE TITLE
backward compatibility in 'Registration & Heartbeat Performance Optimization'

### ISSUE THREAD

**Issue by shichaoyuan** [polarismesh/polaris#457]
https://github.com/polarismesh/polaris/pull/440

在该 pr 中通过心跳 ttl 判断是否走异步注册逻辑，对于 grpc-java-polaris 这种封装 sdk 存在不向后兼容的问题。

对于这种问题有两个选项：
1. 增加额外的标识 internal-instance-asyncregis: true，保持向后兼容
    新版 sdk 加上该标识，走优化后的逻辑，否则走老逻辑
2. 不向后兼容，给用户提供 sdk 与 polaris-server 的版本匹配列表

**Comment by andrewshan** [comment]
主要是在哪个场景下不向后兼容？

**Comment by shichaoyuan** [comment]
> 主要是在哪个场景下不向后兼容？

@andrewshan  以 grpc-java-polaris  为例，现在 sdk 的实现逻辑是 注册一次+周期性心跳，那么如果用户还使用该版本，并且设定了心跳ttl，而 polaris-server 用了性能优化后的新版本，就会有问题。

**Comment by chuntaojun** [comment]
> > 主要是在哪个场景下不向后兼容？
> 
> @andrewshan 以 grpc-java-polaris 为例，现在 sdk 的实现逻辑是 注册一次+周期性心跳，那么如果用户还使用该版本，并且设定了心跳ttl，而 polaris-server 用了性能优化后的新版本，就会有问题。

应该是如果server异步写DB失败的话

**Comment by chuntaojun** [comment]
客户端新增一个RegisterInstanceV2（类似），然后通过添加 grpc metadata的形式来进行开启
