### ISSUE TITLE
Automatically hide some system-level services of Polaris and not show it to the outside world

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#459]
**What is the feature you want to add?**

Automatically hide some system-level services of Polaris and not show it to the outside world

**Why do you want to add this feature?**

Avoid system-level services being modified by users through the console, thus affecting the normal operation of the Polaris system

**How to implement this feature?**

**Additional context**

**Comment by chuntaojun** [comment]
- 需要针对北极星的一些服务进行列表隐藏
  - 控制台接口不得将这些系统服务返回给用户
  - 系统服务配置，建议本次走 polaris-server.yaml 配置
  - 后续北极星服务端的配置应当结合北极星配置中心

**Comment by GuiyangZhao** [comment]
pls assign to me

**Comment by chuntaojun** [comment]
功能代码应当在这里完成：func (sc *serviceCache) GetServicesByFilter(serviceFilters *ServiceArgs,

**Comment by GuiyangZhao** [comment]
pls assign to me
