### ISSUE TITLE
 POLARIS_HOME environment variable is not defined  execute the install script .\tool\start.bat

### ISSUE THREAD

**Issue by ddfeiyu** [polarismesh/polaris#468]
**Describe the bug**
when i execute the install script .\tool\start.bat

**To Reproduce**
Steps to reproduce the behavior.

![1655964572521](https://user-images.githubusercontent.com/104772676/175227487-a4a84f68-a226-42c9-96ea-ec2fff58274a.jpg)

 .\tool\start.bat
The POLARIS_HOME environment variable is not defined correctly
This environment variable is needed to run this program

**Expected behavior**
Description of POLARIS_HOME

**Environment**
- Version:  v1.9.0
- OS: Window 10

**Additional context**

**Comment by chuntaojun** [comment]
ok, we will resolve it

**Comment by andrewshan** [comment]
set "SERVER_NAME=polaris-server.exe"
set "CURRENT_DIR=%cd%"
if not "%POLARIS_HOME%" == "" goto gotHome
set "POLARIS_HOME=%CURRENT_DIR%"
if exist "%POLARIS_HOME%\%SERVER_NAME%" goto okHome
cd ..
set "POLARIS_HOME=%cd%"
cd "%CURRENT_DIR%"

**Comment by andrewshan** [comment]
POLARIS_HOME is set in start.bat

**Comment by andrewshan** [comment]
![image](https://user-images.githubusercontent.com/45474304/175881684-cf192cfb-2b78-4094-9784-aad95a508e9c.png)
I can run and start polaris-server in win10 sucessfully, can you please give me more specific errors?
