### ISSUE TITLE
配置中心支持token验证

### ISSUE THREAD

**Issue by SkyeBeFreeman** [polarismesh/polaris#472]
**What is the feature you want to add?**
配置中心支持token验证
**Why do you want to add this feature?**
配置中心部署在公网环境安全访问需求
**How to implement this feature?**
参考“服务注册与发现”的token认证方式
**Additional context**

**Comment by SkyeBeFreeman** [comment]
From issue of Spring Cloud Tencent, [配置中心支持token验证 #275](https://github.com/Tencent/spring-cloud-tencent/issues/275).

**Comment by chuntaojun** [comment]
see this issue #338

**Comment by SkyeBeFreeman** [comment]
Got it.
