### ISSUE TITLE
Will there be any support for Dubbo governance in the future

### ISSUE THREAD

**Issue by JavaLionLi** [polarismesh/polaris#473]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by JavaLionLi** [comment]
Hope to provide support for Dubbo dynamic routing, fusing and current limiting

**Comment by JavaLionLi** [comment]
希望支持 dubbo 3

**Comment by chuntaojun** [comment]
have contributor in the community working on this task

**Comment by andrewshan** [comment]
hello, these features have already supported in this project https://github.com/polarismesh/polaris-java-agent

**Comment by JavaLionLi** [comment]
> hello, you said is dubbo3 go or java?

java dubbo3.0

**Comment by andrewshan** [comment]
It would be a splendid idea, would you want to contribute?

**Comment by JavaLionLi** [comment]
> It would be a splendid idea, would you want to contribute?

Unfortunately, I don't know enough about Polaris at present

**Comment by chuntaojun** [comment]
在 https://github.com/polarismesh/polaris/issues/783 进行跟踪
