### ISSUE TITLE
win10使用Git Bash安装，ulimit -n 409600 超过最大3200限制，导致安装失败

### ISSUE THREAD

**Issue by 12345ZMTHL** [polarismesh/polaris#487]
![企业微信截图_20220628105029](https://user-images.githubusercontent.com/46614808/176081482-0790c3a2-a02f-4fbf-b942-69b20d1b5010.png)

**Comment by chuntaojun** [comment]
you can see here: https://zgserver.com/windows-git-bash-ulimit.html

**Comment by 12345ZMTHL** [comment]
> you can see here: https://zgserver.com/windows-git-bash-ulimit.html

不好意思，我对shell不是很熟悉，for n in {9999..255}; do ulimit -n $n 2>/dev/null && echo $n && break; done 3200 这句要怎么改呢？

**Comment by chuntaojun** [comment]
不，这只是测试在 gitbash 下 ulimit 可以设置的最大值，这里是 gitbash 本身的约束设置，您可以尝试在 wsl 或者linux虚拟机下，同时 polaris 本身也提供在 window 下的安装包

**Comment by 12345ZMTHL** [comment]
> 好的，gitbash的最大值是3200，这个是可以确定的了，我尝试下后面的解决方案

**Comment by 12345ZMTHL** [comment]
> 不，这只是测试在 gitbash 下 ulimit 可以设置的最大值，这里是 gitbash 本身的约束设置，您可以尝试在 wsl 或者linux虚拟机下，同时 polaris 本身也提供在 window 下的安装包

方便发一下window 版本的安装包嘛？我看README并没window相关的介绍，下图是我构建后生成的目录
![企业微信截图_20220628113638](https://user-images.githubusercontent.com/46614808/176086804-513b4041-7565-497b-b512-075032fc6fb3.png)

**Comment by chuntaojun** [comment]
在这里，可以从我们的 release 中下载：https://github.com/polarismesh/polaris/releases

**Comment by chuntaojun** [comment]
window 的启动命令是 ./tool/start.bat

**Comment by 12345ZMTHL** [comment]
> window 的启动命令是 ./tool/start.bat

多谢
