### ISSUE TITLE
支持i18n国际化

### ISSUE THREAD

**Issue by SkyeBeFreeman** [polarismesh/polaris#525]
**What is the feature you want to add?**

控制台后端返回支持i18n国际化。

**Why do you want to add this feature?**

控制台显示信息或异常统一语言，而不是中英文夹杂。

**How to implement this feature?**

可以看下`go-i18n`。

**Additional context**

无。

**Comment by chuntaojun** [comment]
- 北极星的错误码对应的描述信息，需要参考怎么结合 i18n 的方式，按照header中传来的 Languge 返回对应语种的描述信息
- 仅针对 code_info.go 中的描述做 i18n

**Comment by GuiyangZhao** [comment]
pls assign to me
