### ISSUE TITLE
配置文件过多页面显示不全

### ISSUE THREAD

**Issue by slowmoon** [polarismesh/polaris#537]
![image](https://user-images.githubusercontent.com/22251152/174221511-53d497e9-7f9a-4ab9-91e4-50237bafad81.png)

1，如图所示，当某一个空间下的配置很多，页面上显示的配置不全，也没有分页？
2，配置文件搜索，未和后端进行交互？

**Comment by lepdou** [comment]
@slowmoon 
这个看了一下，当文件比较多的时候，左侧目录区域，没有自动上下滚动。导致有部分文件被遮住了，我们这个版本就优化掉。
