### ISSUE TITLE
解压windows集群安装包，修改了polaris-server.yml的store配置，mysql执行了脚本，运行start.bat后，命令窗一直停在这里。需要输入什么？

### ISSUE THREAD

**Issue by pandaapo** [polarismesh/polaris#538]
![1658670664363](https://user-images.githubusercontent.com/35672972/180650185-f51303ea-ccc3-4a0d-ade2-81e58a578bac.png)

**Comment by chuntaojun** [comment]
有看过进程在运行中吗？

**Comment by chuntaojun** [comment]
> 启动成功后，对polaris windows集群版安装包又有了新的好奇。 polaris server：polaris-server.exe和start.bat两个是什么关系，是前者启动server后者启动一些定时任务吗？不运行start.bat有什么影响？ polaris console：console的start.bat有没有什么特别的作用？

start 脚本会拉起北极星进程，同时会设置一个类似 crontab 的逻辑来定时检查 server 是否运行中
