### ISSUE TITLE
Linux 或  Docker 下 单机版 polaris 搭配 mysql 该如何安装

### ISSUE THREAD

**Issue by Jansora** [polarismesh/polaris#569]
场景:
当我想使用 polaris 的 server 和 console 的搭配 作为 spring cloud config 的后台组件时发现 polaris 的 server 和 console 的安装搭配MySQL 时有点复杂, 
希望能提供  
1. polaris 的 server 与 MySQL 的的搭配使用场景 demo 
2. polaris 的 server 与的搭配使用场景 demo 

以上在 Linux  下的原生安装 demo 或 Docker 下的安装 demo

**Comment by andrewshan** [comment]
好的，我们可以提供一下

**Comment by chuntaojun** [comment]
- 单机版本 + mysql 配置文档
- 单机 k8s 支持两种部署模式
- docker-compose 部署测试

预计在 1.12.0 进行 release
