### ISSUE TITLE
能否加上接口的调用统计功能

### ISSUE THREAD

**Issue by XW512** [polarismesh/polaris#572]
能否在polaris中添加调用量统计功能，这样能更好的显示接口的调用量占比与调用量的分布，对于监测接口的展现，感谢感谢！

**Comment by andrewshan** [comment]
你这边期望具体是在哪里增加比较好，能否详细描述？

**Comment by XW512** [comment]
> 你这边期望具体是在哪里增加比较好，能否详细描述？

感谢回复，我想的是能否在限流那边添加一个这样的功能，在限流那应该是有调用量统计的

**Comment by edocevol** [comment]
statis 插件通过prometheus应该有足够的客户端metrics信息了

**Comment by XW512** [comment]
> statis 插件通过prometheus应该有足够的客户端metrics信息了

这个是监控上，我想的是能否在面板上的展示，这样对于观察者的话，更直观明了

**Comment by onecer** [comment]
> > statis 插件通过prometheus应该有足够的客户端metrics信息了
> 
> 这个是监控上，我想的是能否在面板上的展示，这样对于观察者的话，更直观明了

貌似这个需求同样属于 #271 这个Issue的范畴
