### ISSUE TITLE
支持polaris发布的配置文件下载到微服务的某个路径下

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#583]
**What is the feature you want to add?**

refer：https://github.com/Tencent/spring-cloud-tencent/issues/513

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by XW512** [comment]
这个应该是spring-cloud-tencnet这个框架支持就可以了吧，不需要polaris进行处理？因为拉取配置是spring-cloud-tencent，而不是polaris

**Comment by chuntaojun** [comment]
> 这个应该是spring-cloud-tencnet这个框架支持就可以了吧，不需要polaris进行处理？因为拉取配置是spring-cloud-tencent，而不是polaris

在SCT侧已有同学具体回复了

**Comment by chuntaojun** [comment]
polaris-java以及 polaris-go才是负责真正配置拉取的动作，SCT等只是拿到北极星SDK拉取到配置的结果

**Comment by XW512** [comment]
> polaris-java以及 polaris-go才是负责真正配置拉取的动作，SCT等只是拿到北极星SDK拉取到配置的结果

嗯嗯，好的
