### ISSUE TITLE
standalone模式下安装prometheus失败

### ISSUE THREAD

**Issue by lyramilk** [polarismesh/polaris#591]
**Describe the bug**
我的机器上己经装了别的prometheus，在install.sh安装的时候北极星自带的prometheus就没有装上去。建议installPrometheus这里能优化精准一些。。

**To Reproduce**
先安装一个prometheus,再安装standalone模式的北极星。

**Expected behavior**
希望在己安装prometheus的情况下也可以正确安装北极星自带的prometheus。

**Environment**
- Version: v1.10.0
- OS: Ubuntu 22

**Additional context**
比如修改installPrometheus函数获取prometheus_num的代码加个grep ${prometheus_port}
local prometheus_num=$(ps -ef | grep prometheus | grep ${prometheus_port} | grep -v grep | wc -l)

**Comment by andrewshan** [comment]
好的，看看是否愿意提交个PRfix一下？

**Comment by chuntaojun** [comment]
we will fix in milestone 1.12.0
