### ISSUE TITLE
通过接口注册实例希望能添加健康检查功能

### ISSUE THREAD

**Issue by lyramilk** [polarismesh/polaris#593]
通过http接口注册进去的实例无法进行健康检查，导致注册进去的实例没有办法真正投入使用。希望能尽快加上这个机制。

**Comment by andrewshan** [comment]
好的，能讲一下你们的接入场景么？

**Comment by lyramilk** [comment]
> 好的，能讲一下你们的接入场景么？

目前缺少python的sdk，我想通过http接口把我的python服务注册进去，但因为缺少健康检查功能无法实现自动踢掉实例的操作。
不仅是python，对于任何新的场景，打通http接口的 注册->健康检查->发现 整个环节都是很必要的。

**Comment by chuntaojun** [comment]
当前是可以通过 http 接口进行主动上报实例心跳的

curl --location --request POST 'http://127.0.0.1:8090/v1/Heartbeat' \
--header 'Content-Type: application/json' \
--data-raw '{
    "namespace": "",
    "service": "",
    "host":"",
    "port": 80
}'

**Comment by lyramilk** [comment]
> 

多谢解答。
希望这个办法能补充到文档中。这样后面的人就可以通过文档知道这一点了。

**Comment by chuntaojun** [comment]
> > 
> 
> 多谢解答。 希望这个办法能补充到文档中。这样后面的人就可以通过文档知道这一点了。

好的，我这里来补充下
