### ISSUE TITLE
使用docker安装polaris-server-standalone，重启容器后新建的数据被清空

### ISSUE THREAD

**Issue by 77321660** [polarismesh/polaris#594]
**Describe the bug**
使用docker安装polaris-server-standalone，重启容器后新建的数据被清空
**To Reproduce**
1、安装容器：
docker run --name polaris -d -p 15010:15010 -p 8080:8080 -p 8090:8090 -p 8091:8091 -p 8093:8093 -p 8761:8761 -p 9000:9000 -p 9090:9090  polarismesh/polaris-server-standalone:latest
2、进入管控台新建命名空间：test
3、重启容器
docker restart polaris
4、再次进入管控台，查看命名空间 test 不见了

**Comment by andrewshan** [comment]
单机版的数据都是存储在本地文件polaris.bolt的，容器运行的话，可以把polaris.bolt挂载到宿主机磁盘中，这样重启就不会丢失数据

**Comment by andrewshan** [comment]
单机版的docker安装指南，可以把如何挂盘的方式写上去

**Comment by onecer** [comment]
> 

挂盘貌似解决不了问题，他现在只是restart,理应哪怕不挂载 polaris.bolt 也会存在。是run.sh 引用了install.sh。而install.sh会判断目录是否存在，存在则删除。

```
  if [ ! -e ${polaris_server_dirname} ]; then
    echo -e "${polaris_server_dirname} has exists, now remove it"
    rm -rf ${polaris_server_dirname}
  fi
  unzip ${target_polaris_server_pkg} >/dev/null
```

改为

```
  if [ ! -e ${polaris_server_dirname} ]; then
      unzip ${target_polaris_server_pkg} >/dev/null
  fi
```

即可，下面的console一样的处理

**Comment by 77321660** [comment]
把容器的root目录挂载到主机同样会丢失，你可以测试一下看看。发自我的 iPhone在 2022年8月26日，14:50，andrew shan ***@***.***> 写道：﻿
单机版的数据都是存储在本地文件polaris.bolt的，容器运行的话，可以把polaris.bolt挂载到宿主机磁盘中，这样重启就不会丢失数据
