### ISSUE TITLE
配置文件编辑和查看全屏支持

### ISSUE THREAD

**Issue by 77321660** [polarismesh/polaris#595]
**What is the feature you want to add?**
配置文件编辑和查看全屏支持
**Why do you want to add this feature?**
配置内容较多时，全屏查看和编辑更友好
**How to implement this feature?**

**Additional context**

**Comment by chuntaojun** [comment]
最新的控制台代码已经支持了

**Comment by chuntaojun** [comment]
我们会在下一个版本迭代带上
