### ISSUE TITLE
关于polaris的命名空间

### ISSUE THREAD

**Issue by MI-cool** [polarismesh/polaris#598]
使用polaris-standalone-release_v1.11.0-beta.2.linux.amd64版本服务端，polaris-sidecar-release_v1.3.0-alpha.2.linux.amd64版本sidecar测试dns解析时发现，service好像没有所谓的隔离，但是service的后端节点有隔离。
然后服务别名在不同命名空间可以创建同名服务，这里是不是需要调整一下？

**Comment by chuntaojun** [comment]
服务别名在不同命名空间可以创建同名服务
-----
这个是可以的，不会做限制

**Comment by chuntaojun** [comment]
sidecar测试dns解析时发现，service好像没有所谓的隔离，但是service的后端节点有隔离

---
这是什么意思？

**Comment by MI-cool** [comment]
> 

举个例子，当前pod运行在default namespace，在polaris上手动注册一个服务svc-test到其它namespace并添加一个后端节点。此时在当前pod执行dig svc-test会返回10.4.4.4，但执行http请求时流量进入envoy后会返回503

**Comment by MI-cool** [comment]
> 

再次验证，已无此问题。可能是我当时搞错了
