### ISSUE TITLE
支持灰度发布的场景化能力

### ISSUE THREAD

**Issue by andrewshan** [polarismesh/polaris#631]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by andrewshan** [comment]
##蓝绿发布

蓝绿部署需要按照服务当前版本所占用的资源状况为服务新版本申请同样的资源规格，部署完毕之后将流量整体切换到服务新版本。

- 实例打标。需要新部署一套全量的灰度环境，所有的并且对新的灰度环境打上新版本的标识，并且通过环境变量设置透传标签为version。
- 部署实例：通过SCT自动注册的方式，或者通过k8s controller同步的方式，将实例标签注册到注册中心上。
- 设置流量规则：部署完成后，使用网关的路由能力，将全部流量，切换到新版本上。（需要给出各个网关的使用方式：ENVOY/SCG/NGINX等）
- 微服务路由（自动）：微服务框架自动根据透传的版本标签进行路由，只会路由到相同版本的实例。
- 灰度完成：灰度完成后，对老版本进行缩容，然后去掉流量规则。

![image](https://user-images.githubusercontent.com/45474304/188564793-1115e37f-875b-4a43-bf96-1152b63727f7.png)

**Comment by andrewshan** [comment]
## 金丝雀发布

金丝雀发布允许引流一小部分流量到微服务新版本，待验证通过后，逐步调大流量，充分验证微服务新版本的稳定性。

应用场景一：通过域名隔离进行金丝雀灰度

**Comment by JasonChen86899** [comment]
想问下目前协议透传的功能已经有了么

**Comment by andrewshan** [comment]
> 想问下目前协议透传的功能已经有了么

SCT社区已经排入了这个需求，预计月底会支持：https://github.com/Tencent/spring-cloud-tencent/issues/563

**Comment by baerwang** [comment]
这个需求做了吗，如果没有做是否可以分配给我？

**Comment by chuntaojun** [comment]
> 这个需求做了吗，如果没有做是否可以分配给我？

北极星自身的需求已经完成了～

**Comment by chuntaojun** [comment]
> 这个需求做了吗，如果没有做是否可以分配给我？

剩下的是关于SDK的适配新的路由规则以及支持协议透传，比如 grpc-go-polaris、cloudwego-kitex-polaris这些
