### ISSUE TITLE
日志输出还有几个TODO，貌似挺长时间了

### ISSUE THREAD

**Issue by MI-cool** [polarismesh/polaris#647]
**What is the feature you want to add?**
统一管理日志文件

**Why do you want to add this feature?**
plugin组件的日志配置是不是也放到bootstrap.logger那里统一管理比较好？

下面两个的日志路径还不支持配置
`plugin/discoverevent/local/event_local.go`
`plugin/history/logger/history_logger.go`

**Comment by chuntaojun** [comment]
这里应该用 common/logger 中的方法统一创建 logger，plugin 的 logger 配置应该在 plugin 中的 Options 中去处理

**Comment by chuntaojun** [comment]
@MI-cool  您这里有兴趣帮忙共建下吗

**Comment by chuntaojun** [comment]
see issue #672
