### ISSUE TITLE
北极星的 discover event 添加插件，支持上报到 loki 中

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#648]
**What is the feature you want to add?**

**Why do you want to add this feature?**

- 最简单实现服务实例事件的统一存储，作为北极星开源侧的最简单实现

https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki

**How to implement this feature?**

**Additional context**

**Comment by alexwanglei** [comment]
assign me
