### ISSUE TITLE
eureka协议中针对心跳上报错误码的兼容问题

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#669]
**Describe the bug**

eureka instance的心跳如果遇到server端没有对应实例，server端会返回404，但是polaris这里返回的好像是400

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by lbbniu** [comment]
assign me

**Comment by chuntaojun** [comment]
have pr to fix it
