### ISSUE TITLE
优化插件中logger的配置以及生成

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#672]
**What is the feature you want to add?**

- 每个 plugin 可以调用 commonlog.RegisterScope 注册自己想要的日志 Scope
- commonlog 中添加 GetScopeByName(xxx)的方法，获取一个 logger
  - 如果不存在，则默认输出到 polaris-default 中

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris/issues/647

**Comment by hoErYu** [comment]
请问下是不是在log的type中增加PluginScope，然后plugin下的所有日志都用这个来处理还是都用defaultScope的

**Comment by chuntaojun** [comment]
> 请问下是不是在log的type中增加PluginScope，然后plugin下的所有日志都用这个来处理还是都用defaultScope的

我补充了下这个issue，可以看看
