### ISSUE TITLE
protobuf编译脚本支持多系统环境

### ISSUE THREAD

**Issue by onecer** [polarismesh/polaris#691]
**What is the feature you want to add?**

目前我们common/api/v{1,2}/build.sh 只支持了linux环境的编译。

common/api/protoc 只提供了Linux版本的二进制

**Why do you want to add this feature?**

而我们开发的时候，Windows和macOS的同志就比较麻烦。我们工具对版本有要求的话，找一样的版本也不容易。

是不是可以兼容下不同系统环境的场景。

**How to implement this feature?**

添加不同系统的二进制文件，脚本支持自动判断当前系统环境或者根据参数，调用不同版本的工具完成操作。

**Additional context**

**Comment by onecer** [comment]
是不是把二进制放到对象存储比较好点。然后目录按照以下结构

`$URL/$TOOL_GROUP/$TOOL_VERSION/$OSTYPE/$OSARCH/$TOOL_NAME` 存放

比如 `cos.qcloud.com/protoc/v1.2.0/Linux/x86_64/protoc.all.tgz`
`cos.qcloud.com/protoc/v1.2.0/Linux/x86_64/protoc-gen-go.bin.tgz`

然后下载处理就

```
TOOL_VERSION=v1.2.0
# return eg. Darwin Linux
OSTYPE=$(uname -s)
# return eg. x86_64 arm64
OSARCH=$(uname -m)
PROTOC=../protoc
RPOTOC_BIN_BASEDIR=${PROTOC}/bin/${OSTYPE}/${OSARCH}
if [ ! -d $RPOTOC_BIN_BASEDIR ];then
    mkdir $RPOTOC_BIN_BASEDIR
    wget -O $RPOTOC_BIN_BASEDIR/protoc.all.tgz https://cos.qcloud.com/protoc/$TOOL_VERSION/$OSTYPE/$OSARCH/protoc.all.tgz
   tar zxvf $RPOTOC_BIN_BASEDIR/protoc.all.tgz  -C $RPOTOC_BIN_BASEDIR/
fi

${RPOTOC_BIN_BASEDIR}/protoc \
--plugin=protoc-gen-go=${RPOTOC_BIN_BASEDIR}/protoc-gen-go \
--go_out=plugins=grpc:. \
--proto_path=${PROTOC}/include \
--proto_path=. \
model.proto client.proto service.proto routing.proto ratelimit.proto circuitbreaker.proto configrelease.proto \
platform.proto request.proto response.proto grpcapi.proto config_file.proto config_file_response.proto \
grpc_config_api.proto  auth.proto
```

再添加gitignore 忽略这个二进制目录，原来的Linux的可以保留

**Comment by andrewshan** [comment]
了解你的场景，可以区分多系统来进行编译，在脚本中，通过goos和goarch等环境变量，然后二进制的话，优先看看本地有没有，没有的话，可以去远程进行下载

**Comment by onecer** [comment]
## protoc部分
尝试过通过os类型和架构来判断，然后下载不通的protoc。
通过uname -m和go env GOARCH 获取的值基本不能直接拼凑出protoc的文件名，这个一步需要硬编码的东西太多了。
比如 
[protoc-3.20.0-rc-1-linux-aarch_64.zip](https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0-rc1/protoc-3.20.0-rc-1-linux-aarch_64.zip)
[protoc-3.20.0-rc-1-linux-x86_64.zip](https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0-rc1/protoc-3.20.0-rc-1-linux-x86_64.zip)
[protoc-3.20.0-rc-1-osx-x86_64.zip](https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0-rc1/protoc-3.20.0-rc-1-osx-x86_64.zip)
[protoc-3.20.0-rc-1-win64.zip](https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0-rc1/protoc-3.20.0-rc-1-win64.zip)

比较难替换比如 protoc-$PROTOC-VERSION-$GOOS-$GOARCH.zip 是不够通用的。看了下go-zero 对于protoc的处理，也做不了比较通用。

要通过变量判断，则需要大量的硬编码和大量的不同系统的配置。

此外新版本protoc和老的protoc 1.2.1，proto文件要求有点不太一样，新版本需要执行option package。要直接下载官方的proto，那就要升级protoc版本了。

## 暂定方案

改造 build.sh，其它环境通过docker来在linux环境下编译。用最小的代价支持大部分的需求。
