### ISSUE TITLE
优化北极星的自注册逻辑

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#700]
**What is the feature you want to add?**

北极星的自注册的流程，应当在所有的 apiserver 都正常启动之后，才能执行自注册动作

**Why do you want to add this feature?**

北极星的自注册的流程, 没有等带所有的 apiserver 资源都启动成功后就触发自注册，不是很严谨。由于 apiserver 启动和自注册是两个异步的动作，可能自注册成功了，但是 apiserver 这个时候发现启动有问题，触发北极星server的正常停机动作。如果加上自动拉起脚本的话，那么会使得这个北极星服务端节点不断处于实例注册、反注册的过程。

因此，对于北极星服务端的自注册的触发时机，应该等待所有的北极星功能模块均正常启动之后，在触发自注册动作

**How to implement this feature?**

**Additional context**

**Comment by reallovelei** [comment]
这个是不是 可以用cond wait的方式？
每个组件完成后都 Signal()一下,
主逻辑 cond.wait() 等待所有组件完成

**Comment by chuntaojun** [comment]
> 这个是不是 可以用cond wait的方式？ 每个组件完成后都 Signal()一下, 主逻辑 cond.wait() 等待所有组件完成

可以，其实主要就是需要一个接收全部成功的信号，全部都 ready 之后，在进行自注册

**Comment by chuntaojun** [comment]
> 这个是不是 可以用cond wait的方式？ 每个组件完成后都 Signal()一下, 主逻辑 cond.wait() 等待所有组件完成

有兴趣参与解决下不～
