### ISSUE TITLE
鉴权插件优化：鉴权身份凭据的获取应当在插件中实现，而不能固定死该逻辑

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#709]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by alexwanglei** [comment]
assign me

**Comment by chuntaojun** [comment]
@alexwanglei 可以现在这个 issue 下面回复下你的设计想法
