### ISSUE TITLE
资源鉴权匹配规则支持前后缀匹配

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#710]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by dongyinuo** [comment]
这个任务需要做吗？ 有人认领了吗？

**Comment by chuntaojun** [comment]
> 这个任务需要做吗？ 有人认领了吗？

目前没有人，有意愿搞一下吗

**Comment by dongyinuo** [comment]
嗯嗯，我认领一下吧

**Comment by dongyinuo** [comment]
> > 这个任务需要做吗？ 有人认领了吗？
> 
> 目前没有人，有意愿搞一下吗

嗯嗯，我认领一下吧

**Comment by chuntaojun** [comment]
> > > 这个任务需要做吗？ 有人认领了吗？
> > 
> > 
> > 目前没有人，有意愿搞一下吗
> 
> 嗯嗯，我认领一下吧

可以先想想这一块的设计方案，以及怎么支持存量的鉴权规则
