### ISSUE TITLE
Unstable, fails to deregister on Github Action CI tests

### ISSUE THREAD

**Issue by Davincible** [polarismesh/polaris#732]
Polaris fails to sometimes deregister a service when running tests.

The tests pass fine locally (although with big wait times), but fail altogether in GitHub Actions.

When registering, it comes back as successful. But when subsequently querying for the services to make sure they are gone, they're still present.

Logs: [GitHub Actions](https://github.com/go-micro/plugins/actions/runs/3223730816/jobs/5274108198)
Test: [Here](https://github.com/keepstep/plugins/blob/main/v4/registry/polaris/polaris_test.go)

GH Actions runner: Ubuntu
Polaris Version: Latest beta, although also with earlier versions

**Comment by chuntaojun** [comment]
On the sdk side, the cache is used. The read server will update the cache regularly, and then the updated cache will be downloaded to the SDK side. This is the reason why the github-action itself has rain. The real-time performance of the cache cannot be guaranteed. It is recommended not to use the cache. In the time.Sleep method, it is recommended to directly call the Polaris open-api to check the instance, or use the watch capability on the SDK side to judge the instance change event

**Comment by Davincible** [comment]
I see, but why does the cache work locally but not on GH actions? Because the server is too small?

How can I disable the cache? I would read the docs but they're entirely in Chinese.

**Comment by chuntaojun** [comment]
cache cannot be closed at present, because the data interaction between the server and the SDK is based on the server cache

**Comment by chuntaojun** [comment]
On github-action, the performance of the machine provided by github-action is mainly reduced. Polaris itself has many asynchronous tasks of coroutines, which may cause the cache refresh not to be a stable refresh.

**Comment by Davincible** [comment]
So currently it's not possible to run tests on github actions?

**Comment by chuntaojun** [comment]
you need to adjust the logic in the test, reduce the use of time.Sleep as much as possible, use the following code method, use the watch ability of the SDK to process

```go
watchReq := api.WatchServiceRequest{}
watchReq.Key = key
watchRsp, err := consumer.WatchService(&watchReq)
c.Assert(err, check.IsNil)
channel := watchRsp.EventChannel
```

or directly call the OpenAPI interface of ${polaris-server-ip}:8090 

```bash
GET /naming/v1/instances? service=&namespace=&offset=&limit=
```
