### ISSUE TITLE
sidecar模式限流无效

### ISSUE THREAD

**Issue by MI-cool** [polarismesh/polaris#736]
**Describe the bug**
单机模式部署，配置单机限流规则后envoy无法解析限流规则
<img width="1560" alt="wecom-temp-274563-f642f250ddb846428164a1e1921d33c8" src="https://user-images.githubusercontent.com/9128391/195496533-9b87cfbd-f763-44f9-b43f-c96460c170ec.png">

**To Reproduce**
单机模式部署，配置单机限流规则

**Expected behavior**
限流生效

**Environment**
- Version: [最新版本]
- OS: [k8s]

**Comment by andrewshan** [comment]
我们看看

**Comment by andrewshan** [comment]
https://github.com/polarismesh/polaris-sidecar/issues/51
