### ISSUE TITLE
polarismesh/polaris-server-standalone镜像未正常启动 prometheus和 polaris-limiter

### ISSUE THREAD

**Issue by clover2022** [polarismesh/polaris#737]
**Describe the bug**

https://github.com/polarismesh/polaris/blob/main/deploy/standalone/vm/Dockerfile
缺少COPY    polaris-limiter-release*.zip

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: v1.2.0
- OS: [e.g. CentOS8]

**Additional context**

**Comment by andrewshan** [comment]
我们看看，有具体的错误信息么？

**Comment by chuntaojun** [comment]
i will fix today
