### ISSUE TITLE
自定义路由中匹配规则里的正则表达式不生效

### ISSUE THREAD

**Issue by juye2005** [polarismesh/polaris#749]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42275114/196079758-24cd0b71-84b7-4879-aa33-99a2cf7eae36.png)
![image](https://user-images.githubusercontent.com/42275114/196079952-9ead0749-02d2-4c9e-81bf-c7c5a9b69057.png)
![image](https://user-images.githubusercontent.com/42275114/196080112-0cd6b50d-a312-4ca3-98cf-43525e45419c.png)

**To Reproduce**
直接配置正则规则的路由就能复现
![image](https://user-images.githubusercontent.com/42275114/196080185-4e757ee7-3e91-4dda-98ff-8d989229c924.png)

**Expected behavior**
正则表达式运作正常

**Environment**
server版本：polarismesh/polaris-server-standalone    latest           4b27c3b10f0a（image id）
CONTROLLER_VERSION:v1.3.0
SIDECAR_VERSION:v1.3.0-beta.1

**Additional context**
使用bookinfo示例程序 注入了envoy和polaris-sidercar

**Comment by andrewshan** [comment]
我们看看

**Comment by andrewshan** [comment]
经排查，是XDS生成过程中，少传了一个字段，导致规则没有生效

caused by StringMatcherValidationError.SafeRegex: embedded message failed validation

caused by field: \"engine_type\", reason: is required):
