### ISSUE TITLE
官方文档的改进意见

### ISSUE THREAD

**Issue by fuxshen** [polarismesh/polaris#762]
1、官方文档图片无法点击放大，对近视阅读者不太友好
2、文档中的部分名词，希望通俗易懂，或者对名词做出详细易懂的解释
3、对具体流程操作步骤以及细节，具体化，标注详细化
4、对部分代码或者部分操作以及配置文件，多添加注释，以及为什么要这么做，
标注操作的具体意义或者作用，在读者使用阅读文档时，尽量做到“开箱即用”

**Comment by chuntaojun** [comment]
收到

**Comment by chuntaojun** [comment]
我们会在新的官网优化任务中把这个处理

**Comment by fuxshen** [comment]
> 我们会在新的官网优化任务中把这个处理

此次官网新的文档，并未对图片点击放大做处理
<img width="936" alt="image" src="https://user-images.githubusercontent.com/59307222/201124245-65d6ace3-cb5f-4990-9b23-92dfe4884a9d.png">

**Comment by fuxshen** [comment]
> 我们会在新的官网优化任务中把这个处理

这次新的官网，图片并不支持点击放大
