### ISSUE TITLE
polaris.checker有多出来的ip

### ISSUE THREAD

**Issue by yanshinian** [polarismesh/polaris#775]
![image](https://user-images.githubusercontent.com/10477865/198814123-f912f4ed-dff5-4685-87ca-2eaf910028ad.png)
服务端版本v1.12.0
这种情况。会导致上报的服务被停止后。依然显示健康状态。不会被置为失效。

**Comment by chuntaojun** [comment]
这个目前可能需要依赖 polaris-cleanup 来做都低措施，我们将这个 polaris-cleanup 也进行放在部署包中

**Comment by chuntaojun** [comment]
我们会在 1.14.0 迭代中彻底解决这个事情

**Comment by daheige** [comment]
https://github.com/daheige/workpool


Take a look at this. Add the task to the pool chan and schedule the task execution through the workpool.


------------------ 原始邮件 ------------------
发件人: liaochuntao ***@***.***&gt;
发送时间: 2022年11月1日 16:32
收件人: polarismesh/polaris ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [polarismesh/polaris] polaris.checker有多出来的ip (Issue #775)





 
我们会在 1.14.0 迭代中彻底解决这个事情

**Comment by chuntaojun** [comment]
预想方案

1. polaris-sever 基于 store 层进行选举一个 Leader 角色
2. 只有 Leader 角色才能执行 polaris。checker 等系统服务实例对账动作、清理不健康实例、清理空实例服务等任务

**Comment by yanshinian** [comment]
收到
