### ISSUE TITLE
希望spring cloud tencent能尽早的适配springboot2.7.3

### ISSUE THREAD

**Issue by dxaitxau** [polarismesh/polaris#781]
近期新项目选型使用polaris，但在接入的时候发现项目使用的springboot2.7.3，而最新的polaris只支持springboot2.6.x，因为现在是项目初期，我们是坚持要使用，所以希望能尽早适配，万分感谢。

**Comment by hoErYu** [comment]
应该去spring cloud tencent社区那边提https://github.com/Tencent/spring-cloud-tencent

**Comment by SkyeBeFreeman** [comment]
可以使用 Spring Cloud Tencent 1.8.1-2021.0.3 版本
