### ISSUE TITLE
配置中心-内容配置不做语法校验

### ISSUE THREAD

**Issue by leoterry-ulrica** [polarismesh/polaris#782]
作为配置中心，配置内容应该需要做语法校验，否则实施人员配置起来太容易犯错误了，而且需要添加配置文件格式化。

**Comment by onecer** [comment]
觉得这个需求合理，我们配置是有格式的选项的，可以在前后端做校验，可以优先考虑后端兜底感觉。

**Comment by chuntaojun** [comment]
> 觉得这个需求合理，我们配置是有格式的选项的，可以在前后端做校验，可以优先考虑后端兜底感觉。
> 
> viper支持配置类型比较多，这个来实现校验可能会简单些。
> 
> ```go
> package main
> 
> import (
> 	"encoding/json"
> 	"fmt"
> 	"strings"
> 
> 	"github.com/pelletier/go-toml"
> 	"github.com/spf13/viper"
> 	"gopkg.in/yaml.v3"
> )
> 
> func configFormatValidator(config string, format string) error {
> 	switch format {
> 	case "json":
> 		return json.Unmarshal([]byte(config), &struct{}{})
> 	case "yaml":
> 		var yml map[string]interface{}
> 		return yaml.Unmarshal([]byte(config), &yml)
> 	case "toml":
> 		_, err := toml.Load(config)
> 		return err
> 	default:
> 		return nil
> 	}
> }
> 
> func validateConfigWithViper(config string, format string) error {
> 	validator := viper.New()
> 	validator.SetConfigType(format)
> 	return validator.ReadConfig(strings.NewReader(config))
> }
> 
> func main() {
> 	confContext := `
> [server]
> port = 8080
> ` // nil 为通过
> 	if err := configFormatValidator(confContext, "json"); err != nil {
> 		fmt.Println(err)
> 	}
> 	if err := validateConfigWithViper(confContext, "toml"); err != nil {
> 		fmt.Println(err)
> 	}
> }
> ```
> 
> 前端如果编辑器能支持错误语法实时标记的话，可能体验会更好点。

优先在前端先支持，后端的配置中心逻辑等优化之后，可以通过插件机制在做支撑

**Comment by chuntaojun** [comment]
该 issue 目前通过 polaris-console 进行了前端配置中心格式检查，在 v1.14.0 版本发布体验
