### ISSUE TITLE
polaris-server 提供日志 SDK，其他应用可以引用 server 的日志实例，减少重复性工作

### ISSUE THREAD

**Issue by edocevol** [polarismesh/polaris#786]
**What is the feature you want to add?**

polaris-server 的日志需要抽取出来，如社区贡献的插件需要写日志，能够有途实现和 polaris-server 同等的日志行为。

需要注意的是，需要保证第三方插件等接入成本低，比如：polaris-server 注册日志实例到 sdk 中，sdk 有全局变量存储日志实例，第三方插件（[loki](https://github.com/polaris-contrib/polaris-server-plugin-history-loki)）通过 SDK 获取日志实例，简便地获取日志能力。

**Comment by chuntaojun** [comment]
目前暂时没有这个考虑
