### ISSUE TITLE
[Bugs] 服务列表，检索按钮失效，无法检测默认条件下的实例

### ISSUE THREAD

**Issue by gotoworld** [polarismesh/polaris#793]
**Describe the bug**
[Bugs] 服务列表，检索按钮失效，无法检测默认条件下的实例

**To Reproduce**
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/8605471/200738051-da71accb-7219-4386-b205-cafc923d663a.png">

**Expected behavior**
<img width="1755" alt="image" src="https://user-images.githubusercontent.com/8605471/200738093-049f148a-cda0-4c26-a950-61e26ef866be.png">

**Environment**
[- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]](http://14.116.241.63:8080/)

**Comment by chuntaojun** [comment]
这里不能把搜索条件去掉，要查询全部实例是需要设置健康状态为全部才可以

**Comment by gotoworld** [comment]
谢谢，如果不可以去掉搜索条件，建议UI上控制下，否则去掉后搜索结果和实际结果不一致。

**Comment by chuntaojun** [comment]
> 谢谢，如果不可以去掉搜索条件，建议UI上控制下，否则去掉后搜索结果和实际结果不一致。

是个好的建议，我们优化下
