### ISSUE TITLE
单机版健康实例数量未减少问题

### ISSUE THREAD

**Issue by 2366567504** [polarismesh/polaris#795]
**Describe the bug**
![image](https://user-images.githubusercontent.com/41350991/200762805-a92f5f1a-4713-4f21-8f31-843aa5de1708.png)
当前健康实例数为1，但实际上该服务中并没有健康的实例。
![image](https://user-images.githubusercontent.com/41350991/200762950-dd65dd17-9ce4-42cc-a252-fbbcf9cfd6e3.png)

**To Reproduce**
1、使用虚拟机安装Centos7.8
2、安装单机版北极星：polaris-standalone-release_v1.12.1.linux.amd64
3、启动过后在IDEA里面注册服务到北极星
4、将IDEA启动的服务关闭
然后就会出现健康实例数的异常问题。
中途如果没出现异常情况则将虚拟机挂起、恢复，然后再次注册服务即可复现。
**Expected behavior**
无

**Environment**
- Version: polaris-standalone-release_v1.12.1.linux.amd64
- OS: Vmware+CentOS Linux release 7.8.2003 (Core)

**Additional context**
无

**Comment by chuntaojun** [comment]
需要确认下，Polaris 命名空间下的 polaris.checker 下是否存在健康实例
