### ISSUE TITLE
The shebang must be on the first line. Delete blanks and move comments.shellcheck(SC1128)

### ISSUE THREAD

**Issue by dyrnq** [polarismesh/polaris#814]
**Describe the bug**

The shebang must be on the first line. Delete blanks and move comments.shellcheck([SC1128](https://www.shellcheck.net/wiki/SC1128))

There are some .sh files begin with comments first line with "# Tencent is pleased to support the open source community by making Polaris available."

**To Reproduce**
cat import-format.sh

**Expected behavior**
A shebang only has an effect when it appears as the first line in a script. 
```bash
#!/bin/bash

# Tencent is pleased to support the open source community by making Polaris available.
#
# Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
#
# Licensed under the BSD 3-Clause License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://opensource.org/licenses/BSD-3-Clause
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

```

**Additional context**

[The shebang must be on the first line. Delete blanks and move comments.](https://www.shellcheck.net/wiki/SC1128)

**Comment by chuntaojun** [comment]
could you create some pr to fix it？

**Comment by dyrnq** [comment]
> could you create some pr to fix it？

I'd like to try
