### ISSUE TITLE
Incomplete image tag of polarismesh/polaris-limiter:##POLARIS_LIMITER_VERSION## in docker-compose.yaml in release package polaris-standalone-release_v1.13.1.docker-compose.zip

### ISSUE THREAD

**Issue by dyrnq** [polarismesh/polaris#844]
**Describe the bug**
Incomplete image tag  polarismesh/polaris-limiter:##POLARIS_LIMITER_VERSION## docker-compose.yaml 

**To Reproduce**
```bash
wget https://github.com/polarismesh/polaris/releases/download/v1.13.1/polaris-standalone-release_v1.13.1.docker-compose.zip
unzip polaris-standalone-release_v1.13.1.docker-compose.zip
cat docker-compose.yaml | grep POLARIS_LIMITER_VERSION
```
**Expected behavior**
##POLARIS_LIMITER_VERSION## need replaced properly before package and release.

**Environment**
- Version: all version

**Additional context**
None

**Comment by chuntaojun** [comment]
will fix in v1.14.0
