### ISSUE TITLE
Please provide the arm64 version of polarismesh image on the DockerHub.

### ISSUE THREAD

**Issue by zoujiaqing** [polarismesh/polaris#853]
The current PolarisMesh image only supports the amd64 architecture:
https://hub.docker.com/r/polarismesh/polaris-server

**Comment by chuntaojun** [comment]
supported in v1.14.x

**Comment by StringKe** [comment]
1.14.x 中 console / limiter 没有 arm64 的版本

使用 docker-compose 部署的方式中 prometheus 和 mysql 的新版本中依旧支持 arm64 了
