### ISSUE TITLE
question：polaris-server的同步是依赖db的同步能力吗？boltdb只适合单机场景使用吗？

### ISSUE THREAD

**Issue by DFSOrange** [polarismesh/polaris#86]

**Comment by chuntaojun** [comment]
1、目前boltdb仅作为单机模式下代替mysql存储
2、集群模式下，所有的polaris-server连接的是同一个DB，共享一个存储

**Comment by jingjiajie** [comment]
> 1、目前boltdb仅作为单机模式下代替mysql存储
> 2、集群模式下，所有的polaris-server连接的是同一个DB，共享一个存储

polaris用mysql是怎么达到百万级client的？像心跳等信息是通过db来同步的吗？我理解mysql应该扛不住

**Comment by chuntaojun** [comment]
> > 1、目前boltdb仅作为单机模式下代替mysql存储
> > 2、集群模式下，所有的polaris-server连接的是同一个DB，共享一个存储
> 
> polaris用mysql是怎么达到百万级client的？像心跳等信息是通过db来同步的吗？我理解mysql应该扛不住

1. mysql只是一个最终的数据存储，每个polaris-server会定时从mysql-server pull 数据进行本地 cache
2. 如果客户端开启了心跳上报，polaris-server 会使用本地memory或者redis，进行心跳计算，只落最终结果
