### ISSUE TITLE
缓存的storeTIme更新异常,通过console更新的service数据，无法正确地同步到SDK

### ISSUE THREAD

**Issue by davionchen** [polarismesh/polaris#869]
**Describe the bug**
通过console修改instances信息

![image](https://user-images.githubusercontent.com/2884774/209088470-add7e9b1-47ff-4348-af20-acf043429b00.png)

通过sdk拉取的的instances信息
![image](https://user-images.githubusercontent.com/2884774/209088657-02bfa39a-b9d8-48d6-86b4-b33fdcb87051.png)

两者不一致。

查看polaris-cache.log，有异常信息:

022-12-20T14:32:36.455434Z     error   cache   cache/store_time.go:47  [Store][Time] watch store time  {"error": "Error 1040: Too many connections"}
2022-12-20T14:37:43.447123Z     error   cache   cache/store_time.go:47  [Store][Time] watch store time  {"error": "Error 1040: Too many connections"}

**Environment**
- Version: 1.12.1

**Comment by shichaoyuan** [comment]
{"error": "Error 1040: Too many connections"}

这个错误信息看起来是 db 连接太多，估计此时已经拉取不到增量数据了。

**Comment by chuntaojun** [comment]
> 

但是用户的反馈是，db 后面恢复之后，还是有一段时间数据没有恢复，问题节点的数据和别的正常节点的数据不一致

**Comment by shichaoyuan** [comment]
@chuntaojun  
又看了一下 watchStoreTime 的逻辑，这里的意图是：如果store时钟回退大于tick的1秒，计算一个diff=pre-cur，这个是个正值。
而 service realUpdate 时是 lastMtime.Add(storeRollbackSec)，这里是否有问题？

不过跟你描述的现象还是不一样。

**Comment by chuntaojun** [comment]
> @chuntaojun 又看了一下 watchStoreTime 的逻辑，这里的意图是：如果store时钟回退大于tick的1秒，计算一个diff=pre-cur，这个是个正值。 而 service realUpdate 时是 lastMtime.Add(storeRollbackSec)，这里是否有问题？
> 
> 不过跟你描述的现象还是不一样。

确实，需要fix处理下

**Comment by shichaoyuan** [comment]
@chuntaojun   感觉这里“基于时间的机制”怎么处理都有些小细节。 如果把 revision 改成单调递增的 bigint， 基于这个数来拉取增量缓存，是否能更好处理一些？

**Comment by chuntaojun** [comment]
> @chuntaojun 感觉这里“基于时间的机制”怎么处理都有些小细节。 如果把 revision 改成单调递增的 bigint， 基于这个数来拉取增量缓存，是否能更好处理一些？

这个属于逻辑大调整了，并且需要调整库表结构设计，其实目前基于时间机制，只是会多拉取数据以及时钟回拨带来的数据拉取丢失问题，这个可以在代码中通过一些简单方案规避的

**Comment by shichaoyuan** [comment]
> > @chuntaojun 感觉这里“基于时间的机制”怎么处理都有些小细节。 如果把 revision 改成单调递增的 bigint， 基于这个数来拉取增量缓存，是否能更好处理一些？
> 
> 这个属于逻辑大调整了，并且需要调整库表结构设计，其实目前基于时间机制，只是会多拉取数据以及时钟回拨带来的数据拉取丢失问题，这个可以在代码中通过一些简单方案规避的

嗯，改动是比较大。
基于现有的机制，感觉可以将 `storeRollbackSec` 默认就回拨 1 秒，如果 watchStoreTime 检查到偏差，再在这个基础上回拨。
