### ISSUE TITLE
1.13.4的linux amd单机版本 安装prometheus报错 无法正常安装

### ISSUE THREAD

**Issue by dnlixiaoxin** [polarismesh/polaris#878]
**Describe the bug**
1.13.4的linux amd单机版本 安装prometheus报错 无法正常安装

**To Reproduce**
bash install.sh
prepare install polaris standalone...
polaris-console listen port info
console_port=8080

polaris-server listen port info
eureka_port=8761
xdsv3_port=15010
prometheus_sd_port=9000
service_grpc_port=8091
config_grpc_port=8093
api_http_port=8090

polaris-limiter-server listen port info
polaris_limiter_http_port=8100
polaris_limiter_grpc_port=8101

prometheus-server listen port info
prometheus_server_port=9090

pushgateway-server listen port info
pushgateway_server_port=
install polaris server ...
/develop/polaris-standalone-release_v1.13.4.linux.amd64/polaris-server-release_v1.13.4.linux.amd64 /develop/polaris-standalone-release_v1.13.4.linux.amd64
2022-12-30T20:05:06	info	start polaris-server
install polaris server success
/develop/polaris-standalone-release_v1.13.4.linux.amd64
install polaris console ...
/develop/polaris-standalone-release_v1.13.4.linux.amd64/polaris-console-release_v1.10.1.linux.amd64 /develop/polaris-standalone-release_v1.13.4.linux.amd64
2022-12-30T20:05:07	info	start polaris-console
2022-12-30T20:05:07	info	add cron for polaris-console
install polaris console success
/develop/polaris-standalone-release_v1.13.4.linux.amd64
install polaris limiter ...
2022-12-30T20:05:07	info	start polaris-limiter
install polaris limiter finish.
install prometheus ...
number of prometheus package not equals to 1, exit

**Expected behavior**

**Environment**
- Version: [1.13.4]
- OS: [ CentOS7]

**Additional context**

**Comment by chuntaojun** [comment]
already fix in v1.13.5
