### ISSUE TITLE
最新版本，配置中心无法动态获取配置

### ISSUE THREAD

**Issue by KouShenhai** [polarismesh/polaris#880]
**Describe the bug**
配置中心-无法动态获取配置（修改完配置后，通过上下文读取的配置没有变化）

**To Reproduce**
![image](https://user-images.githubusercontent.com/48756217/210089831-d8be04e8-e8fe-40ab-8e6d-6aef30e6b745.png)
![image](https://user-images.githubusercontent.com/48756217/210089885-0191d083-8560-43c6-a2c7-6e9c11f2b227.png)
![image](https://user-images.githubusercontent.com/48756217/210090440-72beea8e-9605-4ce1-a64a-56f415fd9010.png)
![image](https://user-images.githubusercontent.com/48756217/210090497-4cb1a21d-8fd6-409b-a7af-c60cc86720f0.png)
![image](https://user-images.githubusercontent.com/48756217/210090546-a8e4e1d5-c541-4ce1-94be-5264b09246f3.png)

**Expected behavior**

**Environment**
- Version: SpringBoot 3.0.1、SpringCloud 2022.0.0、SpringCloudTencent 1.8.2-2022.0.0

**Additional context**

**Comment by chuntaojun** [comment]
这个看下 spring cloud tencent 的 iwiki，以及了解下 spring cloud 动态刷新的 RefreshScope 注解

**Comment by chuntaojun** [comment]
以及参考下这个iwiki：https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E7%AC%AC%E4%B8%83%E6%AD%A5%E5%AE%9E%E7%8E%B0%E5%8A%A8%E6%80%81%E5%88%B7%E6%96%B0%E9%85%8D%E7%BD%AE%E8%83%BD%E5%8A%9B

**Comment by KouShenhai** [comment]
> 以及参考下这个iwiki：https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E7%AC%AC%E4%B8%83%E6%AD%A5%E5%AE%9E%E7%8E%B0%E5%8A%A8%E6%80%81%E5%88%B7%E6%96%B0%E9%85%8D%E7%BD%AE%E8%83%BD%E5%8A%9B

谢谢，我看一下
