### ISSUE TITLE
最新版本单机polaris，配置分组，存在一个以上的配置时只能点击一次，点击第二个配置文件时无效，并且显示刷新配置成功

### ISSUE THREAD

**Issue by dnlixiaoxin** [polarismesh/polaris#882]
**Describe the bug**
最新版本单机polaris，配置分组，存在一个以上的配置时只能点击一次，点击第二个配置文件时无效，并且显示刷新配置成功，看上去是前端bug

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [polaris-standalone-release_v1.13.5.linux.amd64]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by chuntaojun** [comment]
1.13.5 还有这个问题？

**Comment by dnlixiaoxin** [comment]
对就是用最新的试的

**Comment by chuntaojun** [comment]
> 对就是用最新的试的

浏览器缓存刷新下，我测试过了，没发现你这个问题

**Comment by KouShenhai** [comment]
![image](https://user-images.githubusercontent.com/48756217/210198895-c54b5601-42db-4b3c-b3d8-85dad5552f85.png)
![image](https://user-images.githubusercontent.com/48756217/210198926-d1fdea54-241e-44d2-8d73-095186c913e2.png)
需要点击我标颜色的地方，其他的地方无法切换配置文件

**Comment by chuntaojun** [comment]
> ![image](https://user-images.githubusercontent.com/48756217/210198895-c54b5601-42db-4b3c-b3d8-85dad5552f85.png) ![image](https://user-images.githubusercontent.com/48756217/210198926-d1fdea54-241e-44d2-8d73-095186c913e2.png) 需要点击我标颜色的地方，其他的地方无法切换配置文件，希望对你有所帮助

最新的 1.13.5 以及 1.13.4 已经 fix 过这个问题了，如果是集群版本的话，polaris-console 使用 1.10.1 即可，并更新下浏览器缓存

**Comment by dnlixiaoxin** [comment]
> > ![image](https://user-images.githubusercontent.com/48756217/210198895-c54b5601-42db-4b3c-b3d8-85dad5552f85.png) ![image](https://user-images.githubusercontent.com/48756217/210198926-d1fdea54-241e-44d2-8d73-095186c913e2.png) 需要点击我标颜色的地方，其他的地方无法切换配置文件，希望对你有所帮助
> 
> 最新的 1.13.5 以及 1.13.4 已经 fix 过这个问题了，如果是集群版本的话，polaris-console 使用 1.10.1 即可，并更新下浏览器缓存

最新版本的看上去没问题了 不跳了
