### ISSUE TITLE
docker-compose build polaris-server image error

### ISSUE THREAD

**Issue by sun2008mt** [polarismesh/polaris#886]
**Describe the bug**

According to the steps of `polaris/release/standalone/docker-compose/README.md`, mysql and redis can be started, but polaris-server can't.

**To Reproduce**

```shell
cd polaris/deploy/standalone/docker-compose
docker-compose up -d polaris-server
```

**Expected behavior**

polaris-server container loads configs from `polaris-server.yaml` and start up correctly.

**Environment**

- Version: v1.14.0
- OS: Ubuntu2204

**Additional context**

error information detail:

```text
2023/01/05 16:16:54 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
2023-01-05T16:16:54.563595Z	error	i18n/translate.go:48	[i18n][MessageFile] load fail	{"error": "open apiserver/httpserver/i18n/zh.toml: no such file or directory"}
2023-01-05T16:16:54.563648Z	error	i18n/translate.go:48	[i18n][MessageFile] load fail	{"error": "open apiserver/httpserver/i18n/en.toml: no such file or directory"}
[INFO] load config from polaris-server.yaml
[ERROR] open polaris-server.yaml: no such file or directory
[ERROR] load config fail
```

**Comment by chuntaojun** [comment]
v1.14.0 还未正式发布版本，预计下周发布

**Comment by sun2008mt** [comment]
> v1.14.0 还未正式发布版本，预计下周发布

OK，当时是通过下载源码按照 `README.md` 说明，将 `##POLARIS_SERVER_VERSION##` 改为了 `latest`，那可能实际上拉取的是 v1.13.x 版本吧

**Comment by chuntaojun** [comment]
> > v1.14.0 还未正式发布版本，预计下周发布
> 
> OK，当时是通过下载源码按照 `README.md` 说明，将 `##POLARIS_SERVER_VERSION##` 改为了 `latest`，那可能实际上拉取的是 v1.13.x 版本吧

是，我会调整下 README 的说明，然后建议可以从 release 下载 docker-compose 的安装包
