### ISSUE TITLE
存储层新增实例时，批处实现没有对服务加锁

### ISSUE THREAD

**Issue by Cshiyuan** [polarismesh/polaris#891]
**Describe the bug**

存储层的addInstance方法中通过rlockServiceWithID对服务加锁了
但在batchAddInstances批量方法中却没有对服务加锁

**Comment by shichaoyuan** [comment]
这里好像就没必要对 service 加锁

**Comment by Cshiyuan** [comment]
可能的问题就是有可能在添加instance的时候service被删除了，存在脏数据。

**Comment by shichaoyuan** [comment]
嗯 是有这个极端case

**Comment by chuntaojun** [comment]
是否有兴趣修复下这个case？@Cshiyuan

**Comment by chuntaojun** [comment]
will fix in v1.15.0

**Comment by chuntaojun** [comment]
统一在业务层做服务的 lock 操作，保证不会出现脏数据 case

**Comment by shichaoyuan** [comment]
@chuntaojun   `FirstRegis bool` 这个标识我记得是在异步注册的时候加的，也都取消了？

**Comment by chuntaojun** [comment]
> @chuntaojun `FirstRegis bool` 这个标识我记得是在异步注册的时候加的，也都取消了？

这个实际没有使用，移除了，不做过度的优化逻辑了
