### ISSUE TITLE
限流规则删除后，限流逻辑依然存在

### ISSUE THREAD

**Issue by zev-223** [polarismesh/polaris#904]
版本号：1.13.7
在控制台建立的限流规则，如果在执行删除前未设置禁用，该限流规则会一直生效，个人觉得这不太符合正常的操作逻辑。

**Comment by chuntaojun** [comment]
看下客户端的backup目录下，是否还有该限流规则存在

**Comment by zev-223** [comment]
限流规则配置有的，删除backup文件重启项目后, backup中还是会出现

**Comment by chuntaojun** [comment]
> 限流规则配置有的，删除backup文件重启项目后, backup中还是会出现

那就是还是能从服务端拉到，我这里看下
