### ISSUE TITLE
sidecar模式下，路由规则用请求Header等于xxx 匹配问题

### ISSUE THREAD

**Issue by yk133** [polarismesh/polaris#910]
**Describe the bug**
![1675672959358](https://user-images.githubusercontent.com/26220461/216925018-2971bec7-0128-4baf-bfb0-e1564e3cb4f0.png)

如上图设置 user等于test，但是实际使用 user=xxx任何内容都会命中这条路由规则

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: 13.7
- OS: ubuntu 20
- minikube ，k8s 1.22

**Additional context**

**Comment by chuntaojun** [comment]
是跑的这里的例子是吧：https://github.com/polarismesh/examples/tree/main/servicemesh/extended-bookinfo

**Comment by yk133** [comment]
> 是跑的这里的例子是吧：https://github.com/polarismesh/examples/tree/main/servicemesh/extended-bookinfo

是的没错，你可以验证试试看

**Comment by chuntaojun** [comment]
行，我这里看下问题

**Comment by chuntaojun** [comment]
这里没有复现这个问题

**Comment by chuntaojun** [comment]
![Screenshot 2023-02-15 at 15 37 50](https://user-images.githubusercontent.com/23445172/218962649-c0393b41-65db-43c9-a352-ac4b023b2af0.png)

**Comment by ajia-3** [comment]
我也遇到同样的问题，查看polaris-server上的routing没有问题；只要填写请求匹配规则就会不管value是什么值都会命中这条规则。

![image](https://user-images.githubusercontent.com/127270781/223602376-80199cf9-ce49-4508-a4b3-0eb1e0a63e83.png)

这是polaris-side上的一个日志。

Environment

polaris-server: v1.14.0
polaris-controller: v1.3.1
k8s: 1.24.6 (不清楚是否支持？)

**Comment by chuntaojun** [comment]
> 我也遇到同样的问题，查看polaris-server上的routing没有问题；只要填写请求匹配规则就会不管value是什么值都会命中这条规则。
> 
> ![image](https://user-images.githubusercontent.com/127270781/223602376-80199cf9-ce49-4508-a4b3-0eb1e0a63e83.png)
> 
> 这是polaris-side上的一个日志。
> 
> Environment
> 
> polaris-server: v1.14.0 polaris-controller: v1.3.1 k8s: 1.24.6 (不清楚是否支持？)

你这里也遇到路由规则设置了 user=123，user=456 也能作用到这个路由规则？

**Comment by ajia-3** [comment]
> 

是的 没错 ； 我就配了两条 
一个是canary灰度的命中
![image](https://user-images.githubusercontent.com/127270781/223616421-f213e432-79f3-415e-a3b1-3cba46c4aa4d.png)

一个是兜底的
![image](https://user-images.githubusercontent.com/127270781/223616621-8d1060da-0e74-4dbb-a7eb-c2ad1f3e3fd9.png)

只有这两条: X-Polaris-Metadata-Transitive-site-code=123 或者456 xxx 等等 都会命中到canary的pod；一个backend的service有两个pod 一个是canary 一个是stable；envoy和polaris-sidecar都已自动注入；
![image](https://user-images.githubusercontent.com/127270781/223617193-9d552d60-e41d-43e2-a512-076ab5dac754.png)

**Comment by ajia-3** [comment]
> > 我也遇到同样的问题，查看polaris-server上的routing没有问题；只要填写请求匹配规则就会不管value是什么值都会命中这条规则。
> > ![image](https://user-images.githubusercontent.com/127270781/223602376-80199cf9-ce49-4508-a4b3-0eb1e0a63e83.png)
> > 这是polaris-side上的一个日志。
> > Environment
> > polaris-server: v1.14.0 polaris-controller: v1.3.1 k8s: 1.24.6 (不清楚是否支持？)
> 
> 你这里也遇到路由规则设置了 user=123，user=456 也能作用到这个路由规则？

请问大佬 也支持 k8s: 1.24.6 版本的吗

**Comment by chuntaojun** [comment]
> > > 我也遇到同样的问题，查看polaris-server上的routing没有问题；只要填写请求匹配规则就会不管value是什么值都会命中这条规则。
> > > ![image](https://user-images.githubusercontent.com/127270781/223602376-80199cf9-ce49-4508-a4b3-0eb1e0a63e83.png)
> > > 这是polaris-side上的一个日志。
> > > Environment
> > > polaris-server: v1.14.0 polaris-controller: v1.3.1 k8s: 1.24.6 (不清楚是否支持？)
> > 
> > 
> > 你这里也遇到路由规则设置了 user=123，user=456 也能作用到这个路由规则？
> 
> 请问大佬 也支持 k8s: 1.24.6 版本的吗

支持

**Comment by chuntaojun** [comment]
我用了这个demo ：https://github.com/polarismesh/examples/blob/main/servicemesh/bookinfo/README.md

然后我的路由规则还是跟上面的一样，没有验证出你们这个问题，方便加一个微信更详细的了解下吗？

**Comment by ajia-3** [comment]
观察polaris-server也是通过xds 下发了路由规则 规则也是没有问题；
![image](https://user-images.githubusercontent.com/127270781/223619403-5cc75d3d-f2ca-42de-a9b7-a9522c82d2a9.png)
但是在polaris-sidecar这边看到这条日志；不知是否因为sidecar请求不到polaris-server来同步mesh的配置？
![image](https://user-images.githubusercontent.com/127270781/223619778-2e820232-a333-4f8b-b1d6-77bab3ba5464.png)

**Comment by chuntaojun** [comment]
sidecar自己的域名请求是不会被拦截的，这个应该是最终sidecar会有一个兜底dns解析获取到最终的ip返回给应用侧
这里你业务能够调用成功的话，那就表示sidecar的mesh dns模式正常工作了，将流量导入到了envoy里面

**Comment by ajia-3** [comment]
> 

用的是mesh模式 流量也是确实导入到envoy了 才可以成功调度的。disable路由规则之后就恢复随机LB；不知道是否和兜底这条的指定IP有关 这个是原先的 我都没有动过。
![image](https://user-images.githubusercontent.com/127270781/223621140-d642a399-705e-4032-9312-b0bdd399b0f4.png)

**Comment by chuntaojun** [comment]
这个表示访问10.4.4.4这个ip的请求全部会被拦截到envoy去

**Comment by chuntaojun** [comment]
问题应该不在这里，还是在envoy路由执行这一块

**Comment by ajia-3** [comment]
我这边的环境不存在这个IP

**Comment by chuntaojun** [comment]
这个是这样子的，域名请求先到 polaris-sidecar，sidecar会把在满足要求的域名，固定返回10.4.4.4，这样子业务就会去访问10.4.4.4，从而可以被envoy拦截，这个10.4.4.4 的设置在 polaris-sidecar 内部设置的

**Comment by ajia-3** [comment]
连带着还会出现另外一个问题就是：当路由配置要在被调服务配置两个实例分组 权重都是100 优先级不同时 会出现业务访问时出现no health upsteam
![image](https://user-images.githubusercontent.com/127270781/223623074-841f3344-fcc9-4dfa-8651-88d0fb97147b.png)
偶尔就会出现 
![image](https://user-images.githubusercontent.com/127270781/223623261-76cfc68a-6637-49fb-914f-7e09797c21e0.png)

**Comment by chuntaojun** [comment]
> 

实例分组优先级这个在envoy是无法支持的，从1.14.x开始北极星的路由规则中也不在对外暴露实例分组优先级的理解和设置，所有实例分组均为同等优先级，流量分配比例通过权重处理

**Comment by chuntaojun** [comment]
header 等规则匹配失效的原因已找到，需要更新 controller 的 envoy 版本

**Comment by chuntaojun** [comment]
使用新的 polaris-controller 版本：https://github.com/polarismesh/polaris-controller/releases/tag/v1.4.0
