### ISSUE TITLE
实例状态筛选选全部，目前控制台默认只显示健康实例导致一些非正常下线的实例找不到删除的方式

### ISSUE THREAD

**Issue by sky-0914** [polarismesh/polaris#929]
实例状态筛选选全部，目前控制台默认只显示健康实例导致一些非正常下线的实例找不到删除的方式。
点进服务里，默认只展示健康实例，如果不知道健康状态筛选就无法找到异常状态的实例进行删除。
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/25810110/219528384-55828324-226a-482b-b0be-b5acbd194a67.png">

**Comment by phature** [comment]
补充一下业务建议，看了一下数据库，删除是做逻辑删除的。建议这块改成在线服务、离线服务两个标签页，把删除业务变更为离线，这样业务上更好理解，然后实现一套自动离线的功能，比如某个服务的最后一个实例都离线超过1天，就认为服务实际上离线了。

**Comment by chuntaojun** [comment]
1. 新版本的控制台已经默认展示全部状态的实例了
2. 后续会在 1.15.x 版本中支持自动清理不健康的实例
