### ISSUE TITLE
通过envoy可直接支持服务注册

### ISSUE THREAD

**Issue by zxb448126** [polarismesh/polaris#994]
**Describe the bug**
目前envoy需依赖k8s等实现服务注册，如果在虚机部署，无法直接通过envoy进行服务注册

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
期望在虚机部署envoy，可同时实现服务发现和注册，使用hds等实现方案

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by chuntaojun** [comment]
直接实现 hds 即可完成

**Comment by longkai** [comment]
hello，这个issue我来跟进
